### ISSUE TITLE
Automated color overwrite with bootstrap is not working properly

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#111]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
Standard bootstrap colors are used.

**What you expected to happen**:
Webpack should build a combined css with overwritten colors from _variables.scss.

**How to reproduce it (as minimally and precisely as possible)**:
Set config.toml to not use left over overwrite files `css = []`.

**Comment by mpourismaiel** [comment]
Removing everything from `css` config and changing a color in `static-main/styles/bootstrap-overwrite` would change the color in the final stylesheet. I think I'm not understanding something.

**Comment by mpourismaiel** [comment]
So should I move those colors to overwrite scss fiels?

**Comment by stp-ip** [comment]
I would say yes. That would give the theme the distinctive theme colors and we could remove the left over overwrite css from exampleSite. But maybe I'm missing something. Any drawbacks or what was the reasoning behind not doing it?

**Comment by mpourismaiel** [comment]
I'm ashamed to say I didn't notice the overwrites in there. I just moved the files referenced in head.html

I'll move those variables to overwrite files then.
