### ISSUE TITLE
Add support for RTL stylesheet 

### ISSUE THREAD

**Issue by mpourismaiel** [okkur/syna#115]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
Can not use another stylesheet instead of Syna's own stylesheet altogether. This causes users not being able to use RTL stylesheets or change the stylesheet from ground up.

**What you expected to happen**:
Import another main stylesheet instead of Syna's main one. Removing the main stylesheet from the final build from the user side.

**How to reproduce it (as minimally and precisely as possible)**:
Try to use another stylesheet. I.E. run rtlcss on default stylesheet and use the resulting bundle.

**Anything else we need to know?**:

**Environment**:
- Syna Theme version:  
- Hugo version:  
- Others:

**Comment by stp-ip** [comment]
I assume it's a bad idea, but we could have js and css be it's own global fragment. To switch it out even for single pages would be possible.

Much more modular, but so much harder to grasp and I assume will be the root of a lot of questions in the long run.

**Comment by stp-ip** [comment]
Let's keep this small in scope. I would say add a global switch to config.toml and we provide 2 stylesheet variants. One RTL and one LTR.

**Comment by mpourismaiel** [comment]
Okay that's really good. Thanks.

**Comment by stp-ip** [comment]
Happy to do something different, but it felt like us providing out of the box or native support for RTL would be better than giving some hints on how to do a manual overwrite. Especially with people familiar with RTL on the team. It sounded a bit like a final decision, was more meant to be a I think this could be the way to go. Always happy to discuss.

**Comment by mpourismaiel** [comment]
I'm not sure how to use the config.toml for this without Hugo allowing for running commands for pipelines. It is however possible to make use of environment variables on `yarn dev` or `yarn watch-js`. I'll see what Hugo plans for pipelines and move on from there.

**Comment by stp-ip** [comment]
Is RTL support basically done via JS or where is that injected in your view?

**Comment by mpourismaiel** [comment]
There is [rtlcss](https://github.com/MohammadYounes/rtlcss) which is written with JS. You run it (either with webpack or separately) and it will toggle the right/left values and create a new css file.
