### ISSUE TITLE
Move all dependencies to being self hosted

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#131]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
Currently there are still external dependencies.

**What you expected to happen**:
Self host deps to be tracking minimal out of the box.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
#86

**Comment by mpourismaiel** [comment]
I guess there is only `fontawesome` that is not local and that's due to it not being available on npm. Making it local would make upgrading it harder. Would that be okay?

**Comment by stp-ip** [comment]
Ok let me check around fontaswome.
