### ISSUE TITLE
Support custom CSS and JS injections

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#132]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
We currently have the option to inject additional css and js and overwrite via Hugo. It's currently not possible to disable assets.

**Anything else we need to know?**:
Currently working:
* css + js injection via config.toml config
* `exampleSite/static` overwrites the same file in `theme/static` <-- can be used to overwrite our files

Is this enough. Easy injection, more advanced replacement.

Related: #86

**Comment by mpourismaiel** [comment]
I think with global assets it's better to add them to the css/js array we already have. To disable them one can only remove them from the array. With fragment assets I guess a disableAsset option would do the trick. Also if the global js file is not active all the fragment js scripts would fail. If that's a problem we would consider we should use a boolean to disable all the js scripts.

**Comment by stp-ip** [comment]
One edge case with having all needed global assets in the array would be breaking changes. Users need to keep the array updated even if they don't change anything. 

Taking your suggestion into account. This would lead to 2 options:

1. focus on modularity
* global assets in css/js array
* disableAsset per fragment

2. focus on ease of use
* only inject assets via css/js array
* disableAsset possible via overwriting fragment or css/js file in the page specific `/static/`/`/layouts/`folder
* global overwrite possible via css/js file overwrite in the page specific `/static/` folder

@lauragift21 What is your take on this?
