### ISSUE TITLE
Update Changelog for v0.11.0

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#133]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
Currently changelog is not updated with the latest changes.

**What you expected to happen**:
Updated changelog for v0.11.0 release.

**Comment by mpourismaiel** [comment]
I don't understand some of the changes. Is it okay if I document my own PRs and @lauragift21 would do the same for hers?

**Comment by stp-ip** [comment]
Yeah I think it's a more collaborative PR. So not a one person should take it type of issue.
