### ISSUE TITLE
Provide ready to clone exampleSite?

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#135]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
Currently exampleSite is not easily clonable and pushable to netlify for users.

**What you expected to happen**:
Maybe it might make sense to also provide a exampleSite repo with a submodule of the theme. This would enable easy clone, change, push to netlify workflows.

**Comment by mpourismaiel** [comment]
That will introduce some problems. 
Submodules are locked in the main project. So if we introduce any change in the `exampleSite` (and we're using branches and waiting for PRs to be accepted) we need to switch the HEAD of `exampleSite` submodule and that change will be committed in the main repository. That would mean for each change in the theme that requires a change in the example we're going to have two separate branches with one keeping the other in check. That would be too much of a headache IMO.

**Comment by stp-ip** [comment]
Good point. Just a small clarification. We would still do development within the main repo and change the examples there. The separate and clonable exampleSite would only be updated on releases so we shouldn't need much branching.

**Comment by mpourismaiel** [comment]
Oh ok. If that's the case then we would need to change our git flow a bit. Assuming we create a new repository which contains a simple Hugo website (created by `hugo new site`) and includes `exampleSite` contents, a themes directory with Syna inside and slightly changed `config.toml` file so the `themes` variable would work. If this is going to be the case I think it's a good idea to have the master branch of Syna reflect the latest release and create a new `development` branch and do the development (merging PRs and hot changes) in that branch. Then we can add Syna as a submodule inside the example repo. That way the user can close the example repo and develop it as they want and from time to time update the Syna submodule and if there is a release, fetch it.

**Comment by stp-ip** [comment]
Considering that it adds a bit of a dev burden and it needs a bit of release/update documentation, I would push that into v0.12, if you agree.

**Comment by mpourismaiel** [comment]
That would be great.
-- 
Regards,
Mahdi Pouresmaiel

**Comment by mpourismaiel** [comment]
I think this should be marked as closed since we have an starting point for it and can have related issues in there.

**Comment by stp-ip** [comment]
Yeah I agree. We should close this and create issues in the separate repo. Will create one issue to make our readme document the new way to start.
