### ISSUE TITLE
Add graph fragment

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#139]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What you expected to happen**:
Really rough idea. Provide a stats fragment for open startup stats and or similar

**Anything else we need to know?**:
https://www.openstartups.net/

**Comment by mpourismaiel** [comment]
This is doable with the items fragment currently by simply adding an icon or image, title and content. Do we need something else?

![image](https://user-images.githubusercontent.com/14017717/46617646-1bc8a780-cb2a-11e8-93ad-d2471ceda3c3.png)

**Comment by mpourismaiel** [comment]
I like the JSON approach a bit more. We already have it for editor so I think it makes sense to go with that.

So we would have a graph fragment, which would contain the usual title and subtitle and a json file that would be used by a graphing library in the frontend. Resulting in something like this:

![image](https://user-images.githubusercontent.com/14017717/46669852-766f0b80-cbdd-11e8-8a01-7801e94353b1.png)

Is that correct?

**Comment by stp-ip** [comment]
JSON is easier to script with, but the markdown table approach might also make sense as an additional option later, if we decide to deprecate tables and use markdown tables by default.

For now JSON is fine.

**Comment by stp-ip** [comment]
Btw. nice side effect from using JSON is that one could start by providing the JSON statically and later it could be provided via the events fragment or just a general api call to an endpoint.
