### ISSUE TITLE
Remove left-over config in config.toml

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#146]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
Global disable configuration is still available in config.toml

**What you expected to happen**:
Globally disabling contact form and fontawesome code might not be the best choice anymore.

**Comment by mpourismaiel** [comment]
I think with fontawesome can't be disabled from anywhere else. It's being imported from `head.html` and the font icons are spread between several fragments. I'll remove contact disable in the meanwhile.

**Comment by stp-ip** [comment]
Ah correct. Thanks for checking. Happy to remove only contact and leave fontawesome.
