### ISSUE TITLE
Netlify asset concatenation breaks form.

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#15]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
Concatenation on netlify breaks form checks.

**What you expected to happen**:
Netlify shouldn't be impacting functionality.

**How to reproduce it (as minimally and precisely as possible)**:
Use concatenation and forms. 404 on html5.js etc., which breaks form.

**Environment**:
- Syna Theme version:  v0.7.0
- Hugo version:  v0.30.2

**Comment by stp-ip** [comment]
Needs to be tested with the latest refactoring. Might be able to do that this weekend.

**Comment by stp-ip** [comment]
Waiting for a few issues to be included in Syna to prevent redoing migrations multiple times.

**Comment by mpourismaiel** [comment]
@stp-ip How can I test this issue?

**Comment by stp-ip** [comment]
* setup example netlify side
* configure contact form
* check, if all works out of the box

That would mainly check the contact form code and netlify integration. Selfhosted contact form stuff can de tested later.

**Comment by mpourismaiel** [comment]
Ajax works fine. Unfortunately for checking in fact formspree received the data I need a premium account which is not possible for me :D 

I think with webpack the problem is resolved. But if you need to check anything else check this [deploy](https://suspicious-bohr-572472.netlify.com/). I'll add you to the repo so you can change the config.

**Comment by stp-ip** [comment]
Yeah they recently switched to require a premium account. I'll should be able to test the custom implementation tomorrow. Formspree should work also, also there is always an issue tracker for bug reports :smiling_imp:

**Comment by mpourismaiel** [comment]
Should we consider this closed?

**Comment by stp-ip** [comment]
Almost. Should be closed with my last tests by the end of the week.

**Comment by stp-ip** [comment]
Seems fixed. Another issue came up, but don't think it is related to concatenation.
