### ISSUE TITLE
Use html minification from Hugo

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#168]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
Currently adding whitespace reduction is tedious.

**What you expected to happen**:
Don't reduce whitespace via go template features, but reduce it at build time via Hugo.

**Comment by stp-ip** [comment]
Defaulting to {- ... -} everywhere instead ^^

**Comment by mpourismaiel** [comment]
Do you mean we should write the parser and add the default rule as well?

**Comment by stp-ip** [comment]
A parser seems kind of overkill. We could just use whitespace removal all the time without looking for the perfect html output.

**Comment by stp-ip** [comment]
Let's wait for Hugo to enable minification of HTML and then just don't remove any whitespace by default. That seems like the best solution in my view. Makes dev output a bit more horrible, but shouldn't be much of an issue.
