### ISSUE TITLE
Contact form submission with recaptcha enabled isn't calling correct handler

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#171]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
Contact form submission redirects instead of working in the background.

**What you expected to happen**:
Work asynchronously.

**How to reproduce it (as minimally and precisely as possible)**:
https://about.seetheprogress.com/#contact <-- as example

**Comment by mpourismaiel** [comment]
I'm trying to debug it for the past hour and have only figured out something is wrong with recaptcha submission. When recaptcha is enabled and user clicks on the submit button the function that submits the form is not calling the event handler set by the validator. Just an FYI so you can change the title.
