### ISSUE TITLE
No scss file ?

### ISSUE THREAD

**Issue by nicolas-75** [okkur/syna#19]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
No .scss file was found on the master so theme can't be updated

**What you expected to happen**:
Find all the .scss files on the project to be able to update the theme

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Syna Theme version:  0.8.0
- Hugo version:  0.30.2
- Others:

**Comment by stp-ip** [comment]
Thanks. Good find. Will add the bootstrap scss files next chance I get.

Sorry for the delay, fell through my github notifications.

**Comment by stp-ip** [comment]
Added the files in master. Will also work on a simplified version scss for easily changing colors.

**Comment by stp-ip** [comment]
Added a set of simplified scss sets to more easily overwrite the colors. Also moved the color overwrites into the exampleSite and config.
So no overwrite -> bootstrap defaults
ExampleSite -> uses Syna color overwrites generated via scss

Should be included in the next release.
