### ISSUE TITLE
Sitemap includes /index/

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#195]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
With our current workaround for the root page "/" we have a duplicate page as `/index/` is also showing up within the sitemap.

**What you expected to happen**:
Hide or workaround `/index/`.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Maybe use deplicated fragment code with index.html and then get these fragments (special case) from _index/

**Comment by mpourismaiel** [comment]
Whenever the new release from Hugo comes out we can fix this and blog quite neatly I think. Right now there's the problem with getPage where we can't be sure what page is received when we call getPage with a common page name like `_global`. With the new release this will be fixed. So we can have `_index` and `_global` pages in any section. `_global` is to have global fragments and `_index` is for the section pages, aka list pages using list layouts. As mentioned in the Hugo docs home page uses the same mechanism so we can have a content file to let Hugo know that we want a section level page or a list page and have a `_index` directory to store the fragments for that page and `_global` in any section to have section level global fragments. Does that sound good?

**Comment by mpourismaiel** [comment]
I think #258 would fix this one as well. Not sure though. Let's keep it in mind and check for it after the PR is finished.
