### ISSUE TITLE
Add documentation for favicon customization

### ISSUE THREAD

**Issue by dbriesz** [okkur/syna#196]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
The current documentation does not indicate that in order to overwrite the fallthrough favicon, a user-provided favicon should be placed in the static/ directory.

**What you expected to happen**:
Information available in the documentation stating where user-provided favicons should be placed. 

**How to reproduce it (as minimally and precisely as possible)**:
Currently, the documentation contains information about image resource fallthrough and adding images to static/images. In order to use a custom favicon, however, the favicon images need to be placed in the static/ directory.

**Environment**:
- Syna Theme version:  0.11.0
- Hugo version:  0.41

**Comment by stp-ip** [comment]
We do have some custom favicon code, which is different than the default favicon used, which is usually located in /static/favicon.ico.

We have config options to customize the various favicons or provide more than just the simple .ico:
https://github.com/okkur/syna/blob/master/exampleSite/config.toml#L26

This should probably documented. That the default way without custom config is static/favicon.ico, but one can provide more versions/files via the custom config.

Does that seem right?

**Comment by mpourismaiel** [comment]
@stp-ip I can't understand how it's working. I think I need a documentation to write the documentation :D

**Comment by stp-ip** [comment]
Maybe @lauragift21 and @dbriesz can jump in.
Would love to see the perspective. Happy to jump in later and add the docs myself, if necessary.
