### ISSUE TITLE
Basic getting started guide

### ISSUE THREAD

**Issue by dbriesz** [okkur/syna#198]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
The documentation could use a basic getting started guide that demonstrates how to create a single page that shows things like minimum markdown files and directories needed to create that content

**What you expected to happen**:
A section in the documentation for getting started as a user who is new to Hugo themes.

**How to reproduce it (as minimally and precisely as possible)**:
When starting to set up content based on exampleSite, it wasn't evident from the documentation that an index.md file is required in each subdirectory of the content section.

**Environment**:
- Syna Theme version:  0.11.0
- Hugo version:  0.41

**Comment by stp-ip** [comment]
Should be fixed with #223

**Comment by mpourismaiel** [comment]
@stp-ip Can we consider this one closed as well? Since #223 is fixed.
