### ISSUE TITLE
Contact form documentation

### ISSUE THREAD

**Issue by dbriesz** [okkur/syna#199]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
While there is a contact form template, there isn't documentation on how to configure the contact form.

**What you expected to happen**:
A section in the documentation that contains an example or references to external documentation on how to set up the contact form.

**How to reproduce it (as minimally and precisely as possible)**:
Using the contact template from exampleSite contains helpful comments, but could also use supporting documentation.

**Environment**:
- Syna Theme version:  0.11.0
- Hugo version:  0.41

**Comment by mpourismaiel** [comment]
I guess it's much better to have a documentation somewhere and have all the fragments with examples and documentation and guides to set them up. Currently our documentation is only explaining how to setup a website using Syna and how Syna works. So adding fragment specific documentation would make it too complex IMHO.

**Comment by stp-ip** [comment]
We could add one readme per fragment and later expose that on the demo site next to the examples?
