### ISSUE TITLE
Page-top broken

### ISSUE THREAD

**Issue by nicolas-75** [okkur/syna#20]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
Impossible to use #page-top anchor

**What you expected to happen**:
Bring the user to the top of the page

**How to reproduce it (as minimally and precisely as possible)**:
Clic on the logo. #page-top is added on the adress. Go lower then clic on the adress bar and push enter key. Nothing happened

**Anything else we need to know?**:
Add the missing id "page-top" in the layouts/partials/nav.html file to have: `<div class="container" id="page-top">`

**Environment**:
- Syna Theme version:  0.8.0
- Hugo version:  0.30.2
- Others:

**Comment by stp-ip** [comment]
Sorry for the late response. Added the fix in 318b44d will be released with 0.9.0 in the coming week probably.
Thanks for helping out. Really appreciated.

**Comment by nicolas-75** [comment]
With the solution that I proposed, the link always leads to the top of the main page, even when the site has several pages. Unfortunately I do not know why!

Was this test done during the bug fix?

**Comment by stp-ip** [comment]
It depends on how you link to it. The logo is expected to link to the main page usually. That's why we are linking to `/#page-top`, which is the main page. If you want to just link to the top of the page do something like: `/$YourCurrentPage/#page-top`

**Comment by nicolas-75** [comment]
I did not know this variable that is not present in the documentation (https://gohugo.io/variables/page/). So I will use it to put the link in the footer. Thanks to that, users will go up the top of the current page. Thanks for the information !

**Comment by stp-ip** [comment]
It's not a hugo variable. Was more a variable to showcase that you need the current page.
Haven't tested, but I think this should work:
```
[[menu.legalFooter]]
  url = "#page-top"
  name = "Top of the page"
  weight = 10
```
