### ISSUE TITLE
Add theme version to site header

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#200]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
Currently it's hard to see the specific Syna Theme version within a sites header.

**What you expected to happen**:
Show version and commit of site in site header.

**Environment**:
- Syna Theme version: v0.11.0

**Comment by mpourismaiel** [comment]
The proposal issue is closed on Hugo. I can't think of any ways we can add version without Hugo's support.

**Comment by stp-ip** [comment]
We read it from a global variable that is assigned at the top of our template code?
That is manual as we have to change it within that variable, but I could add this to the release tasks and later could be automated maybe.

**Comment by mpourismaiel** [comment]
Sounds good. Will add it to a top level helper like fragments.

**Comment by stp-ip** [comment]
We are currently hardcoding it and have it updated during the release process.
