### ISSUE TITLE
Use short url to link in attribution

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#208]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
Currently within the attribution we link to Github. We should control our own entrypoints.

**What you expected to happen**:
Move that link to a domain we control and redirect accordingly.

**Anything else we need to know?**:
Use https://syna.okkur.io

**Environment**:
- Syna Theme version: v0.11.0

**Comment by stp-ip** [comment]
This needs txtdirect path based routing to be active.

**Comment by mpourismaiel** [comment]
Should I implement the link? Just change the attribution link from Github to syna.okkur.io.

**Comment by stp-ip** [comment]
That way we control the entrypoint. Was first thinking about using something along the lines a separate shortener url such as: s.okkur.io/syna, but that seemed like a weird thing to do as we can just have a specific syna address right away. What do you think?

**Comment by mpourismaiel** [comment]
Specific address seems like a better choice to me.

**Comment by stp-ip** [comment]
Ok so as described in the issue then.
