### ISSUE TITLE
[member] Add company example to single member mode

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#211]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
#204 introduced `company` as a new key.

**What you expected to happen**:
Showcase this field within single member mode within exampleSite.

**Environment**:
- Syna Theme version: master

**Comment by lauragift21** [comment]
I'll take this on but it needs #204 to be merged first.

**Comment by stp-ip** [comment]
Merged \o/
