### ISSUE TITLE
Single member fragment font changes to a light grey color with dark background

### ISSUE THREAD

**Issue by dbriesz** [okkur/syna#215]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
When changing to the dark background in portfolio.md for the single member fragment, the font changes from black to grey and is difficult to read. This applies to the "title", "position", "reports_to" and "lives_in" text in bio.md.

**What you expected to happen**:
The font stays consistent when changing to a dark background for the single member fragment.

**How to reproduce it (as minimally and precisely as possible)**:
Change the background from light to dark in portfolio.md.

**Environment**:
- Syna Theme version: v0.11.0
- Hugo version: v0.41

**Comment by stp-ip** [comment]
Additional info. This is most likely due to us changing the fragment background color, but not the background color of the bubble thing. So if we decide to keep it like this, we should be able to fix this by removing the color switch on the various text items.
