### ISSUE TITLE
Restructure demo

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#216]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug | feature

**What happened**:
Huge index page without a full structure.

**What you expected to happen**:
Structured demo.

Something along the lines of:
```
/ <- see below
fragments/$fragment
background-color/
dev/ <- all testing related stuff
```
The general idea is to split up each fragment into its own subpage.
Each of these subpages then showcases the various variations of said fragment.
Additionally we could add /background-color/ to showcase the background colors.
The index page would consist of:
* hero
* items to explain the features
* table or content to give an overview of the current fragments and link to the various subpages
* newsletter
* copyright

The menu should probably reflect that new structure and basically link to home, imprint/about

Later (when list pages are implemented) we could add links to /fragments and /dev, which just list the subpages of these.

**Anything else we need to know?**:
First actionable item from meta issue #206 

Just a first thought. Happy to discuss this in more detail before someone implements it.

**Comment by lauragift21** [comment]
Regarding this issue. I'll like to take this on. Currently the structure is a bit confusing i agree. What we have now is along the lines of:
```
<_index/
awesome-team
hero 
items
portfolio
```
With some other content files not having a directory if their own.
You talked about adding background, does that mean having a seprate folder with all the background variations for a particular fragment?

**Comment by stp-ip** [comment]
Yeah there are a few issues with the current way we use the member and items fragment data, but that is a separate issue.
I think the first thing we should do is split up the current demo into
dev/
background/ <- As you said showcasing the backgrounds possible. Maybe with the item fragment and iterate through all the backgrounds.
fragment/member/ <- This would showcase both the single member and team member fragment option. Basically each fragment has its own subpage and on that page we can showcase the various options of that specific fragment. Splitting it up further seems too fractured.

The index/root page could in a first step be a general overview of the features using the items fragment and a table with the available fragments, a link to the demo and a link to the code? and a small explanation or so.

**Comment by mpourismaiel** [comment]
With permission from @lauragift21 I'm working on this issue.

I've created a new section called fragments and added each fragment from `_global` and `_index` directories to separate pages, each containing different examples of the same fragment. Also I'm adding the code for each example into the page.

For index and background pages I need a bit help since I'm not sure what content to show in each one. If you have any ideas please let me know.

**Comment by stp-ip** [comment]
Background could be the content fragment with the various possible background colors. Basically each fragment would feature one color and maybe add the code to do this within the content section or so?

**Comment by stp-ip** [comment]
On the index. I would do a first iteration with navigation, hero, items fragment showcasing the main Syna features, a footer and maybe a table or content fragment listing the various fragments and their demo pages?

Basically the index would be the main page for Syna and could later be used as entry page for Syna itself. How that would be done, I'll think about.
