### ISSUE TITLE
[portfolio] align title, subtitle and text vertically

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#226]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
Currently text feels too close to the edge within the modal.

**What you expected to happen**:
Align it with the title and subtitle.

**Comment by mpourismaiel** [comment]
I believe this is fixed.

![arttutor gridpic](https://user-images.githubusercontent.com/14017717/42895432-2f7c9e8a-8acf-11e8-9221-e9818959df56.jpg)

**Comment by stp-ip** [comment]
Yeah, just wasn't auto closed with the merge.
