### ISSUE TITLE
Migrate 404 page to "_global"

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#228]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

Use fragments from "_global". Currently it uses "global" instead.

**Comment by lauragift21** [comment]
Regarding this issue, I can't seem to find any 404 page within the dev/fallthrough/global directory

**Comment by stp-ip** [comment]
Was more related to the layout code: https://github.com/okkur/syna/blob/master/layouts/404.html#L6

Should have been a bit more elaborate with the issue description.
