### ISSUE TITLE
Add local first image files via .Resources

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#23]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
All static files including fragment images are stored in `/static/<fragment>/` and therefore are not bundled close to the actual content.

**What you expected to happen**:
Enabling bundling of images with actual content via .Ressources

**Anything else we need to know?**:
Needs migration to page bundles first #22.
Local first with a fallback to the /static/ folder.

**Comment by lauragift21** [comment]
Does this implementation need something similar to the one here?
```
├── about
│   ├── footer.md
│   ├── header.jpg
│   ├── hero.md
│   └── index.md
├── about-split
```
Having the images in the same content folder for every markdown content that includes an image.

**Comment by stp-ip** [comment]
There are a few options.

My current idea would be (from highest priority location to least):
```
content/index/my-team/gopher.jpg <- fragment specific image
content/index/gopher.jpg <- page specific, but can also be used by fragments
static/gopher.jpg <- global - could be default images etc.
```

Question that might needs to be answered first is how multiple languages would work.
