### ISSUE TITLE
Single member mode for member fragment

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#27]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
Currently each member part is 1/3 of the page making it hard for single member showcasing.

**What you expected to happen**:
Use full page for single members.

**Anything else we need to know?**:
Optional or separate fragment?

**Comment by lauragift21** [comment]
Looking at the changes for member fragment I still need a more in-depth explanation on how we need to separate the member from the page.

**Comment by stp-ip** [comment]
@lauragift21 any update on this? It's still assigned to you, so just wanted to check in.

**Comment by lauragift21** [comment]
Sorry for the delay will work on this now
