### ISSUE TITLE
[404] Reduce image size to w-75 to be closer to the hero design

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#278]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
Image on the 404 page is too big.

**What you expected to happen**:
Make it similar to the hero image. (w-75)

**Comment by mpourismaiel** [comment]
The image size formula for hero logo is the following. `w-75` would be too big.

```
<img class="overlay img-fluid" src="{{ $.root.Scratch.Get "image" | relURL }}"
  {{- if .height -}} height="{{ .height }}"{{- end -}}
  {{- if .width -}} width="{{ .width }}"{{- end -}}
></img>
```

Would that be a good replacement? The following is `w-75`:
![image](https://user-images.githubusercontent.com/14017717/44031558-a17c94aa-9f19-11e8-8c9d-4140017387b8.png)

**Comment by stp-ip** [comment]
Ah right. We switched to height and width customization instead of w-75. Yeah happy to do the same as with hero. Great catch.
