### ISSUE TITLE
Make use of baseOf.html

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#29]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
Currently navigation, footer are partials. These should be moved to baseOf.html.

**What you expected to happen**:
Use baseOf.html.

**Anything else we need to know?**:
https://gohugo.io/templates/base/#define-the-base-template

**Comment by mpourismaiel** [comment]
Correct me if I'm wrong. Basically we need to create a new `_layouts/baseof.html` and import `nav` and `footer` in it. Also remove these partials from other layouts and define and main block around their content.

**Comment by stp-ip** [comment]
Yes correct.
