### ISSUE TITLE
Alert user where to store members/items etc. for specific fragments, when no data available

### ISSUE THREAD

**Issue by lauragift21** [okkur/syna#30]
**Is this a BUG REPORT or FEATURE REQUEST?**: 
 feature

**What happened**: Content files won't be visible except the naming structure is consistent. (i.e `content/index/my-awesome-team.md/` and `content/index/awesome-team.md/`  doesn't match)

**What you expected to happen**: To check if this is working correctly print out the resulting `{{$member}}` if it's empty then print out the location of the files in the command line `{{ printf "%s/*" $name_t }}`

**Comment by stp-ip** [comment]
This might also include the full path.
So instead of printing `my-awesome-team/` it probably should print out the full path as it's easier to grasp:
`content/index/my-awesome-team/`

**Comment by stp-ip** [comment]
@lauragift21 Any update here?

**Comment by lauragift21** [comment]
As far as the current codebase is i think the naming structure is consistent. I'll have a look at all the directories to make sure asap.

**Comment by stp-ip** [comment]
Ok. Should we add a logging message during build, if a fragment relies on additional data being provided via subpaths, but there is no data accessible yet. Aka warn on empty subpaths and print a minimal docs where to save data to?

**Comment by lauragift21** [comment]
Yeah, we should that would be helpful.

**Comment by lauragift21** [comment]
To be more descriptive where could this be added to? as a comment or in the docs

**Comment by stp-ip** [comment]
We should have the method on how subpaths work for items and members in the docs, but this issue itself tracks a "runtime" notice.
Something along the lines of (within member.html and items.html):
If no resources are found, print small documentation on where to add them and a link to further documentation.
