### ISSUE TITLE
[404] Add fragments page specific to 404

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#304]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
Currently the 404 fragment isn't showcased or documented within exampleSite.

**What you expected to happen**:
Showcase and document 404.

**Comment by mpourismaiel** [comment]
404 page can't be shown anywhere except /404.html which is not a good place to showcase it. We can put a screenshot though. What do you think?

**Comment by stp-ip** [comment]
Explanation + screenshot + code should be ok I guess.
