### ISSUE TITLE
Create new image helper

### ISSUE THREAD

**Issue by mpourismaiel** [okkur/syna#305]
Image fallthrough code is scattered around the code and it's making the code a bit too complex. Extract that code into a helper.

This would require images to be declared a bit different. Follow the snippet below:

```
[asset]
  image = "image-path"
  width = ""
  height = ""
  text = ""
```

Or use `assets` where there are more than one image of the same type.

**Comment by stp-ip** [comment]
I assume weight is only defined for [[assets]].

**Comment by stp-ip** [comment]
Also it probably should be:
```
[asset]
  image = ""
  text = "" <- recommended
  width = "" <- optional
  height = "" <- optional
  url = "" <- optional
  weight = "" <- optional - mostly used for [[assets]]
```

And
```
[[assets]]
  image = ""
  text = "" <- recommended
  width = "" <- optional
  height = "" <- optional
  url = "" <- optional
  weight = "" <- optional - mostly used for [[assets]]
```

**Comment by stp-ip** [comment]
Also would we actually use width and height for images within member etc. or would we overwrite that? The only places where we currently allow setting width and height is `hero` and `404`. The rest is usually done responsively without specific settings.

**Comment by stp-ip** [comment]
Also we should add documentation on recommended image sizes or at least ratios to the fragment documentation.
