### ISSUE TITLE
Specific container sizes on the website to prevent layout issues

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#35]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
Currently the image sizes for logos etc. are only recommended and might break the layout.

**What you expected to happen**:
Set a height and max-height or so to keep the layout from breaking.

**Comment by stp-ip** [comment]
Another option would be to use specific sizes on the frontend. So instead of using w-75 we would use a specific width. Maybe check that with various logo sizes, what's the best option.

**Comment by lauragift21** [comment]
I think one option would be using Hugo resize method like use shortcodes to resize the images and then use it within markdown. this gives an idea as to how that would work https://hugo-resource-images.netlify.com/

**Comment by mpourismaiel** [comment]
Tried to work around it as much as I could but sadly it's not possible to do this in a way that's intuitive. Image processing in Hugo only works with page resources and not with files located in `static` directory as stated [here](https://gohugo.io/content-management/image-processing/#the-image-page-resource).

I tried adding the feature inside the image helper but at the end, this would confuse the users. I can write up a script that does this and run it on yarn build but that's not better.

If you have any other solutions in mind I'd be happy to hear them. IMHO we should prevent layout issues using CSS only and trust that users wouldn't try to break their pages.

**Comment by stp-ip** [comment]
Ok let's prevent layout issues with CSS. Maybe add documentation on the recommended ratio/size for the various fragments, now that we have the ability to easily document it "inline" via the content fragments in the fragments directory.

**Comment by stp-ip** [comment]
I think the first step is to mostly set a height and max-height on the container so that the layout doesn't break even with horrible image ratios or sizes. The rest would probably be up to the user to optimize.

**Comment by stp-ip** [comment]
Only thing that feels a bit off is the member circle. In my view it should be a circle.

**Comment by mpourismaiel** [comment]
I've been stuck on this issue for the past two/three days. The latest progress is that when I try to crop the image resource I get an error that says the resource is a generic one not an image one. I'm pushing the branch and creating a WIP PR so if you can take a look I would appreciate it.
