### ISSUE TITLE
Ability to hide navigation bar

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#36]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
Currently the navigation bar is always shown.

**What you expected to happen**:
Ability to disable navigation bar.

**Comment by mpourismaiel** [comment]
I think this issue is kinda dependent of #29 since when that issue is resolved we can just remove the nav from `baseof.html`.

**Comment by stp-ip** [comment]
Not just removing it, but making it optional.
My idea would be to remove the navbar without any menu entries, but have a manual overwrite.
Aka if no menu entry, but `forceNav = true` or something we would still show it.
