### ISSUE TITLE
Move the minimal CSS to the theme side

### ISSUE THREAD

**Issue by mpourismaiel** [okkur/syna#360]
With #319 we have a minimal CSS which is added directly to the HTML in order to have the basic layout of the page if the user doesn't receive the complete CSS. But the minimal CSS needs to be located in the user space since `readFile` function (defined by Hugo) only works in user space and doesn't read any files inside the theme (unless the path is hardcoded which is not reliable).

Track https://github.com/gohugoio/hugo/issues/4842 and whenever it's done or a new feature from Hugo is available which allows us to read a CSS file's content inside the layouts, move the minimal CSS to the theme.

**Comment by stp-ip** [comment]
Can't we reuse `resources.Get` just without the toCSS function? That would be scoped to the theme.

**Comment by mpourismaiel** [comment]
We wouldn't be able to use resources since it's type isn't String, and the lack of any to text functionality makes it impossible to read the file content.
