### ISSUE TITLE
Code snippets are hard to read on dark backgrounds

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#364]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
Currently code snippets are hard to read on darker backgrounds.
See: https://about.txtdirect.org/hosted/

**What you expected to happen**:
We should either invert the text color or add a light background  to code snippets on dark backgrounds.

**Anything else we need to know?**:
Happy for other suggestions. Just wanted to track this.

**Comment by mpourismaiel** [comment]
This is actually fixed in the `dev/colors` PR. Inline code and link is much harder to deal with.

**Comment by stp-ip** [comment]
Idea:
bg-dark + bg-secondary: light background on the code block
all backgrounds: light background on the inline code text

**Comment by mpourismaiel** [comment]
Invert the color on the inline and block codes.

**Comment by stp-ip** [comment]
code block and inline code inverts the text and background color to showcase the difference to normal text.
