### ISSUE TITLE
[exampleSite] Move nesting into /dev/

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#371]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
Leftover nesting test code in exampleSite.

**What you expected to happen**:
Should be moved to /dev/ or removed.

**Comment by mpourismaiel** [comment]
I think removing it would make more sense. We have a lot of examples of nesting page already.

**Comment by stp-ip** [comment]
Sounds good.
