### ISSUE TITLE
[nav] Search doesn't work properly if there are more than one navbar on the page

### ISSUE THREAD

**Issue by mpourismaiel** [okkur/syna#388]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
Search in navbar doesn't work properly

**What you expected to happen**:
To be able to search using any navbar available on the page

**How to reproduce it (as minimally and precisely as possible)**:
Add more than one navbar to the page with search activated on them

**Environment**:
- Syna Theme version:  v0.13
- Hugo version: v0.48
- Others:

**Comment by stp-ip** [comment]
This is a known limitation. Let's keep this out of milestones for now.
