### ISSUE TITLE
[react-portal,editor] React components don't always show up

### ISSUE THREAD

**Issue by mpourismaiel** [okkur/syna#390]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
Editor or other react portals don't always show up

**What you expected to happen**:
To be sure that every react component is always rendered

**How to reproduce it (as minimally and precisely as possible)**:
Checkout `react-portal` or `editor` fragment examples. The issue happens occasionally.

**Environment**:
- Syna Theme version: v0.13
- Hugo version: v0.48
- Others:

**Comment by stp-ip** [comment]
This seems to break frequently now: https://about.okkur.io/syna/fragments/editor/

**Comment by stp-ip** [comment]
Chrome/Chromium seems to work. Problem seems to be mainly with Firefox.
