### ISSUE TITLE
Update header information

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#408]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
```
<meta name="theme" content="Syna Theme - (https://github.com/okkur/syna)">
<meta name="theme description" content="Highly modular open source theme for Hugo built with Bootstrap 4">
<meta name="theme author" content="Okkur Labs - https://okkur.io">
```

**What you expected to happen**:
```
<meta name="theme" content="Syna">
<meta name="theme-version" content="v0.15">
<meta name="theme-url" content="https://syna.okkur.io">
<meta name="theme-description" content="Highly customizable open source theme for Hugo based static websites">
<meta name="theme-author" content="Okkur Labs">
<meta name="theme-author-url" content="https://okkur.io">
```

Thoughts? Especially on the hardcoded version? I'll add that to the release tasks so it gets updated on release. It's not perfect, but at least it would be in the header.

**Comment by mpourismaiel** [comment]
Fantastic. I'll add them to the og fix. Since Hugo didn't add the support for theme variables this is the only way. It's okay for now IMO.
