### ISSUE TITLE
Use text-black and text-white for all text.

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#415]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
Currently we use text-dark and text-light.

**What you expected to happen**:
Use text-black and text-white instead to decouple colorization of light and dark colors from impacting readability.

**Comment by stp-ip** [comment]
Additionally we should remove the usage of text-muted for now.

**Comment by mpourismaiel** [comment]
Removing the muted color would change the design quite a lot. Check this out for example. The subtitle and sidebar content are muted and everything else is using the light color.

**Comment by stp-ip** [comment]
Did you wanna add a screenshot?

**Comment by mpourismaiel** [comment]
Oops. This is with muted:

![image](https://user-images.githubusercontent.com/14017717/47603507-84a09280-d9f9-11e8-927d-e148a89f0c0b.png)

This is with muted:

![image](https://user-images.githubusercontent.com/14017717/47603500-79e5fd80-d9f9-11e8-803d-357636a97630.png)

**Comment by stp-ip** [comment]
I think if nothing is muted it will work best for readability. What do you think?

**Comment by mpourismaiel** [comment]
@stp-ip It would help I think. Will do an iteration and push a PR so we can discuss it.
