### ISSUE TITLE
[list, toc] Nested content should be collapsible

### ISSUE THREAD

**Issue by mpourismaiel** [okkur/syna#416]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
ToC and List fragment can have nested content which would add much more data than what's actually needed for the user to see.

**What you expected to happen**:
The nested content should be collapsible through a variable in the fragment's frontmatter.

**How to reproduce it (as minimally and precisely as possible)**:
Checkout `/docs` page of the demo (after #414 is merged).

**Comment by stp-ip** [comment]
Not sure I see the full context of this issue. Also another variable :(
