### ISSUE TITLE
Netlify form submission support

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#43]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
Currently we support self hosted email sends and formspree.

**What you expected to happen**:
Support netlify contact form submissions.

**Anything else we need to know?**:
https://www.netlify.com/docs/form-handling/

**Comment by mpourismaiel** [comment]
Should the form consider any variables for adding support for Netlify forms?

**Comment by stp-ip** [comment]
Variable to make the user switch to netlify?
Currently we have postURL, which can be set or defaults to formspree.io.

Probably two options.
* remove formspree and use empty case for netlify
* keep formspree and use true/false switch to enable netlify and disable usage of formspree or postURL

All the hidden fields should still be available in netlify.

**Comment by mpourismaiel** [comment]
These won't be much of an issue if we can resolve #12 but I have no idea how to resolve that.

I'll be working on this one. I'll add a new section to config file named `form` and a variable on it called `netlify`. Also I'll add a `name` field on contact form which would satisfy netlify form handling.

**Comment by stp-ip** [comment]
The config is part of the frontmatter of the contact fragment: https://github.com/okkur/syna/blob/master/exampleSite/content/index/contact.md

So a netlify = true/false that overwrites the postURL and formspree handling would work.

**Comment by mpourismaiel** [comment]
Ok so no global overriding for it then. Would that be good?

**Comment by mpourismaiel** [comment]
I made a PR implementing what I believe you requested. Let me know if you had something else in mind. I also recommend adding `netlify` to the global configuration since we can use for other situations if they ever arise. Also it would allow the user to just name the forms and not duplicate `netlify = true` to every (future, custom) fragments.

**Comment by stp-ip** [comment]
The idea behind not having the contact form config globally set, was that one can specify different contact forms for say sales, support etc. all having different fields and different mail addresses.

Globally that wouldn't be possible.
Happy to discuss that further.
@lauragift21 what would be your take on global vs contact.md set contact form configuration?
