### ISSUE TITLE
[demo] Docs link not available

### ISSUE THREAD

**Issue by mpourismaiel** [okkur/syna#431]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
Syna's documentation is not accessible in the Syna demo.

**What you expected to happen**:
To be able to read the documentation.

**How to reproduce it (as minimally and precisely as possible)**:
Visit the demo.

**Anything else we need to know?**:
I'm using https://about.okkur.io/syna/docs in syna-start. If that link can be activated it would be great.

**Comment by stp-ip** [comment]
syna/docs/ is based on v0.15. That means the docs would be for v0.15, while we released just v0.14.
We can do it, just wanted to mention the discrepancy.

**Comment by mpourismaiel** [comment]
Nice word. Didn't know it.
Totally forgot about the versioning on the docs. There are two arguments on this however. One is versioning and the other is that docs would be on the demo page and demo would be showing the latest build. Also the docs are way too out of sync for the release. Should we update the docs according to v0.14 and keep them on Github and in the next release move to docs on website?

**Comment by stp-ip** [comment]
Let's add the docs to the page with the v0.15 release. Keep the old docs link and mention they might be out of date. We can wait for v0.15 to launch on themes.gohugo.io, which also gives users the nice new docs page from the start so it makes sense to push this to v0.15. What do you think?

**Comment by mpourismaiel** [comment]
Should we still keep the old documentations?

**Comment by stp-ip** [comment]
You mean the readme etc.? I think as soon as we have the release and deployed it to okkur.org, we can move to a simple readme having a dev intro and linking prominently to the actual docs hosted on okkur.org. Or?

**Comment by mpourismaiel** [comment]
That sounds good. I didn't really remember the conversation we had on this.

**Comment by stp-ip** [comment]
This is now live. Most changes are live in preparation for v0.15. Currently we have a beta tag out and the v0.15 release branch will get the last fixes in the next few days.
