### ISSUE TITLE
[items] Image/logo only margin is too much

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#441]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
Currently using image only mode the margin on the bottom and top of each image is too much.
Showcasing company logos or so takes up too much space.
Both on mobile and in full screen.

**What you expected to happen**:
Reduce top and bottom margin for image only things.

**How to reproduce it (as minimally and precisely as possible)**:
See https://about.nzt.capital/ as an example.

**Comment by mpourismaiel** [comment]
The only way I can think to fix this is a nested loop in the template which would be messy. Currently we have a height of 200px so the images would line up. Is it okay if we have nested loops?

**Comment by mpourismaiel** [comment]
Also about.nzt.capital looks really nice. I don't think fixing the issue would improve the design in there.

**Comment by stp-ip** [comment]
Going down to say 160px wouldn't work in general?
Also probably a no on nested loops :P
There is always the option to go with portfolio, so that would be another option, but it just feels like too much whitespace in the various screen sizes.
