### ISSUE TITLE
[stripe] Ability to auto send receipts

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#468]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
Currently we don't send a receipt as we don't set the receipt_email.

**What you expected to happen**:
Send receipt by default and make an option to disable on the client side.

**How to reproduce it (as minimally and precisely as possible)**:
Look for sent receipts in our test data.

**Anything else we need to know?**:
I might be missing something due to it not sending the actual receipts in test mode, but I think it should at least show up in the dashboard or?

**Comment by mpourismaiel** [comment]
Fixed in https://github.com/okkur/syna-stripe-gcf/pull/1
