### ISSUE TITLE
[docs] Add docs for item, items, config and iterate

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#480]
Extends #442 

* [x] item
* [x] items
* [x] config
* [ ] iterations
  * [x] [contact: hidden field defaults](https://github.com/okkur/syna/pull/442/files/8a249f708fb6b379e3eaba0b862155b893064604#r245509614)
  * [x] use different background color than code fragment
  * [ ] make toc sticky

**Comment by mpourismaiel** [comment]
I forgot to mention, I'm working on this issue. Config and items seem almost done.

**Comment by stp-ip** [comment]
Awesome. Thanks for taking this on. One less thing to do for me \o/

**Comment by mpourismaiel** [comment]
@stp-ip I feel like we've already added this: `contact: hidden field defaults`. Is there anything more that should be added?

**Comment by stp-ip** [comment]
Happy to close this with the current PR in flight. If anything seems missing, I'll create a new issue.
