### ISSUE TITLE
[stripe] payment shows as successful even so stripe returns error

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#481]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
Payment success is shown.

**What you expected to happen**:
Show payment error.

**How to reproduce it (as minimally and precisely as possible)**:
Use a non supported currency and do a test payment.

**Comment by mpourismaiel** [comment]
I fixed the currency problem so the reproduction steps don't work. Have you seen this issue happen under different circumstances?

**Comment by stp-ip** [comment]
Yes the server responds with a 200 status code, but with an embed error.

The reproduction steps should still work. Just use "yen" as currency, which is the wrong iso code.

But I agree it might be fixed in the backend.  Let's keep it open here until we have a fix here or in the backend.

**Comment by mpourismaiel** [comment]
Fixed in https://github.com/okkur/syna-stripe-gcf/pull/1
