### ISSUE TITLE
[stripe] icon and button accessibility

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#482]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
For icons/buttons such as cancel event overwrite and edit with custom value no alternative text is given. Maybe also add a tooltip on hover?

**What you expected to happen**:
We should be inclusive here and add a default text with translation possibilities.

**Comment by mpourismaiel** [comment]
I think this is under #400. I was going to add some texts and alt/title attributes while handling that issue. Is this different than that?

**Comment by stp-ip** [comment]
Most likely, but wanted to add this specifically as it's relevant from the user side even without accessibility in mind aka the tooltip etc.
