### ISSUE TITLE
[event] (idea) add obfuscated event url handling

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#489]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
Currently we handle human readable urls for events and this might lead to people changing stuff that shouldn't be changed, play around with things they shouldn't etc. Always depends on the use cases.

**What you expected to happen**:
Add an obfuscation layer into event urls.
Simplest case would be to take the whole query string such as `?event=pricing:change&plan=Starting plan&price=42€&currency=eur` and encode it via [base64url](https://tools.ietf.org/html/rfc4648#section-5) resulting in a url such as:
`?e=P2V2ZW50PXByaWNpbmc6Y2hhbmdlJnBsYW49U3RhcnRpbmcgcGxhbiZwcmljZT00MuKCrCZjdXJyZW5jeT1ldXI=`
The idea would be to recognize `?e=` as a shorthand for event, but that is always encoded via base64url. This could then be decoded and applied the same way a non obfuscated url would have been.

**Anything else we need to know?**:
https://tools.ietf.org/html/rfc4648#section-5
https://simplycalc.com/base64url-encode.php

**Specific note**:
This is an obfuscation layer and does not secure (encrypt) any data. Personal data shouldn't be added as event data. The use case is giving a simple non human readable url to make intention harder and reduce issues with typos etc.

Thoughts?

**Comment by stp-ip** [comment]
This is even more needed than I expected. Our prefilled event urls are hard to share on chat clients or social media due to them might getting parsed wrong. Also less of a surprise. So I think we should prioritize this.

**Comment by mpourismaiel** [comment]
I think adding the feature along with an option to entirely disable the support for `?event=pricing:change&plan=Starting plan&price=42€&currency=eur` format seems really good.
