### ISSUE TITLE
Create portfolio layout

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#5]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
No portfolio layout available.

**What you expected to happen**:
Portfolio layout available.

**How to reproduce it (as minimally and precisely as possible)**:
Look for a portfolio layout.

Notes:
Portfolio items should have the following features:
* primary image (for things such as album cover, book cover, company)
* overlay image (ability to overlay primary image with an image)
* title
* subtitle
* summary
* linkable

Questions:
Should we also support them opening in modals instead of having a link? Something along the lines of: If link is given, click will bring you to the link. If no link is given the content will be shown in a modal with title, subtitle and image as header or similar.
Should title, subtitle and summary be defaulting to the one from linked pages? Easier to use for users, but harder to implement and more magic/complexity.

**Comment by mpourismaiel** [comment]
@stp-ip This is an old issue, do you have any new ideas regarding this? I'm going to work on it. Will create a new fragment that will support image fallthrough with all the variables you listed. I'm also thinking that "If link is given, click will bring you to the link. If no link is given the content will be shown in a modal with title, subtitle and image as header or similar." is a good idea if the summary and subtitle are not shown in the main view. The design in my opinion would be along the lines of the following image curtosy of [Folius](https://wrapbootstrap.com/theme/folius-portfolio-template-WB0674NL1)

![image](https://user-images.githubusercontent.com/14017717/42438606-b6475b64-8375-11e8-9aa7-cd2f6d653453.png)

**Comment by stp-ip** [comment]
Nothing especially new in my mind just a few thoughts floating around.

I agree with the link idea. Not sure I like modals. They always feel strange on mobile, but one could always link to a separate page, if one doesn't like modals.

Two other examples: http://backstagecapital.com/crew/ and http://backstagecapital.com/100/companies

If we go for a modal we could use the Content section enabling the user to add more information. If we focus only on Title and Subtitle than I might think it would be easier to overlay them on the portfolio.

Another option (in a second iteration) would be a switch to either show the title + subtitle on hover/click or right away.
