### ISSUE TITLE
[contact] Firefox submission is not async using mailout aka POST usage

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#511]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
Chrome works as expected, but Firefox does a redirect to the POST endpoint instead of an async request.

**What you expected to happen**:
Firefox behaving like Chrome.

**How to reproduce it (as minimally and precisely as possible)**:
https://about.rekkur.com/#contact

**Comment by mpourismaiel** [comment]
Note for further debugging: Checked for `e.preventDefault()`, `e.stopPropagation()` (which shouldn't really matter), `return false` and everything is there on every level and still the problem persists.

**Comment by stp-ip** [comment]
Did take a look at this, but couldn't find anything yet. It should work, but it doesn't :(

**Comment by stp-ip** [comment]
Might have a few hints. Will take another look next week. We'll get this done ;)

**Comment by stp-ip** [comment]
Ok found the root cause.
We are creating a custom Event, which then gets dispatched.
The event is by default created with the attribute `cancelable = false`. This means it won't be affected by any defaulPrevent() etc. and will always be handled aka not be canceled.

Creating a custom event with `cancelable = true` should resolve this. Will see that I get a minimal patch ready in a bit.

**Comment by mpourismaiel** [comment]
Didn't think to check that. Thanks a lot. It's really weird though that Firefox and Chrome both follow the standards and have these kinds of differences.
