### ISSUE TITLE
[header] Inconsistency with alignment for headings and content

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#525]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug?

**What happened**:
We currently center all fragments except for footer text and content text on smaller screens. Within the content fragments it looks a bit weird as markdown headers are left aligned too.

**Anything else we need to know?**:
Should we center the content text too?
Or should we left align headers for content fragments?
Any other ideas?

Example:
![screenshot from 2019-01-27 14-46-26](https://user-images.githubusercontent.com/3768412/51802466-6b9abe00-2242-11e9-9839-1f2f6dbd0dd6.png)

**Comment by mpourismaiel** [comment]
This is mostly a unique issue for small percentage of pages in my humble opinion. Most contents would have few number of headers displayed after the "introduction" part of the content. We can fix the issue by centering the markdown headers quite easily but in my view keeping the alignment as is would be a better option. The second best would be to align the title to the left on the content fragment.

**Comment by mpourismaiel** [comment]
@stp-ip What do you think?

**Comment by stp-ip** [comment]
Oh wow I think that comment didn't make it through my mentions.

Mhh how about we leave it open for now and revisit this in another release?

In my view this is an inconsistency that should be fixed even in edge cases. But it might not have a high priority. My general idea would be to have the margin gone, when it's left aligned, but might need more thinking.
Maybe we'll get more ideas with more pages migrated or using Syna.

**Comment by stp-ip** [comment]
Fixed: #531
