### ISSUE TITLE
[config] Remove legacy configuration js/css in config.toml

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#527]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
We currently use `js/css = ["counter.js"]` within our example site.

**What you expected to happen**:
Migrate this to our new config.js file.

**Anything else we need to know?**:
Does that make sense?

**Comment by mpourismaiel** [comment]
Makes complete sense. That way the counter component's code (which is quite heavy) is not loaded everywhere, making the demo a bit lighter.
