### ISSUE TITLE
Attribution opt-in or opt-out

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#53]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
We started with an opt-out attribution in the footer. Recently during a refactor it was made opt-in.

Probably best to discuss this.
I'm happy with opt-in, but it might be better from an exposure perspective to have it opt-out.

Opt-out: by default the attribution is shown
Opt-in: by default the attribution is hidden

**Comment by lauragift21** [comment]
I think having it has opt-out by default looks good but there should be a comment indicating the ability to opt-in.

**Comment by stp-ip** [comment]
Ok so hidden by default aka we use opt-in. And then have a comment indicating how they can enable/opt-in.

**Comment by lauragift21** [comment]
Yeah that works.

**Comment by stp-ip** [comment]
Merged #56 
We went with the more conservative opt-in method. The user needs to specifically enable attribution.
