### ISSUE TITLE
[exampleSite] Cleanup unnecessary errors within example site 

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#547]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
Currently building exampleSite results in a few errors/warnings.

**What you expected to happen**:
Only print the relevant ones for testing.

**Comment by mpourismaiel** [comment]
I can't find the mentioned errors.

![image](https://user-images.githubusercontent.com/14017717/54194250-04bf2480-44d1-11e9-9b5f-bf957b573afd.png)

**Comment by mpourismaiel** [comment]
Oops, nevermind. It was because of demo_mode.

**Comment by mpourismaiel** [comment]
These errors are due to our /dev section which we use for testing purposes. Do you mean the same errors should not be printed?

![image](https://user-images.githubusercontent.com/14017717/54194429-7a2af500-44d1-11e9-96fd-db2a51b75018.png)

**Comment by stp-ip** [comment]
Due to our /dev section and our use of demo within exampleSite.

Probably can be closed. Felt weird to receive the errors, but exampleSite is for development and having debug mode enabled seems correct. Happy for you to close this, if you agree.

Thanks for checking in and questioning my idea.

**Comment by mpourismaiel** [comment]
Thanks. I'll close this issue and we can revisit if any other errors show up.
