### ISSUE TITLE
Option to make hero fragment more prominent

### ISSUE THREAD

**Issue by jwkvam** [okkur/syna#571]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
I guess I don't have much content in my hero fragment (only a title, subtitle and a couple buttons) so the hero fragment has little vertical height.

**What you expected to happen**:
I would like the allocate more vertical space to the hero fragment (to make it more prominent) and also vertically center the hero elements so it isn't top heavy.

**How to reproduce it (as minimally and precisely as possible)**:
Comment out the asset from hero.md in syna-start, you'll end up with this:
![image](https://user-images.githubusercontent.com/86304/59007128-fc2d7000-87d9-11e9-9e07-da8118e9bc44.png)

**Anything else we need to know?**:
I'm not a frontend engineer or designer so I don't know what's fashionable these days 😬. I can easily modify the hero height to be something like "80vh" or something, but then the text and buttons are still at the top of the div. My css skills are apparently too weak to figure out how to center them or move them around.

**Environment**:
- Syna Theme version:  0.15.0
- Hugo version:  0.55.6
- Others:

**Comment by stp-ip** [comment]
What's the reasoning behind making the hero element more prominent?

**Comment by jwkvam** [comment]
I'm no expert here but personally for a couple reasons:

1. I think it can make a website look for visually interesting and attractive (assuming the hero image is made well).
2. I think it better controls the attention of the user to the message and call to action by limiting the amount of information presented.

That's mainly based on my intuition, what do you think?

**Comment by stp-ip** [comment]
Seems like mostly a design choice. Will let @mpourismaiel jump in with thoughts.
Not opposed.

* [ ] center content
* [ ] maybe optional height setting? (we didn't do this before due to mobile being harder with a set height afaik

**Comment by jwkvam** [comment]
Sounds good, I personally would be happy with just a boolean option and let syna make sensible choices for the height 😬😄(assuming you all agree that this feature is worth it).

**Comment by mpourismaiel** [comment]
I'm sorry for the long delay. I think `minHeight` and centered content sounds good. I'm working on it right now.

You can also create a a copy of the hero fragment from:

`[project root]/[theme dir]/layouts/fragments/hero.html`

to

`[project root]/layouts/fragments/hero.html`

and add your changes and still receive updates. Just keep in mind to merge the updated version with your custom hero fragment to get the latest version.

**Comment by mpourismaiel** [comment]
Isn't the content centered though?
