### ISSUE TITLE
Parse Failed - hugo not defined in patials/head.html

### ISSUE THREAD

**Issue by herostrat** [okkur/syna#572]
bug 

**What happened**:
hugo fails to parse head.html.
The error is:
``` Error: "xxx/themes/syna/layouts/partials/head.html:48:1": parse failed: template: partials/head.html:48: function "hugo" not defined ```

**Environment**:
- Syna Theme version:  Tested with v 15.0 and master
- Hugo version:  Hugo Static Site Generator v0.52/extended linux/amd64 BuildDate: 2018-12-21T15:59:29Z
- Others:

---
**Edit:**
Solved: The hugo version is to old.
https://discourse.gohugo.io/t/function-hugo-not-defined-in-cupper-theme/18968/2

I have to update to 0.53

**Comment by stp-ip** [comment]
Minimal recommended version is v0.55 (latest available: v0.55.6)
