### ISSUE TITLE
Google analytics property has no effect

### ISSUE THREAD

**Issue by autodidaddict** [okkur/syna#578]
bug

**What happened**: No google analytics JavaScript is ever invoked on the static site

**What you expected to happen**: I expected the site's generated code to inject activation of the google analytics script

**How to reproduce it (as minimally and precisely as possible)**: Set a value for _googleAnalytics_ in the `config.toml` file, nothing happens.

**Anything else we need to know?**: In the `js.html` partial, you see this line:
```
{{- template "_internal/google_analytics_async.html" . -}}
```

However, the filename `_internal/google_analytics_async.html` does not exist anywhere in the theme repository, nor does it exist in the example site.

I'm guessing this feature is either not implemented, or how we're supposed to implement it is undocumented.

**Environment**:
- Syna Theme version:  latest
- Hugo version:  latest
- Others: deploying via netlify

**Comment by autodidaddict** [comment]
Per [Hugo internal templates](https://gohugo.io/templates/internal/) docs, I would expect to be able to see my analytics UA code rendered somewhere.

**Comment by autodidaddict** [comment]
I don't know if this means anything, but the Hugo docs say to use:
```
{{ template "_internal/google_analytics_async.html" . }}
```
And what's in the Syna template is:
```
{{- template "_internal/google_analytics_async.html" . -}}
```

Are the minus signs meaningful here?

**Comment by stp-ip** [comment]
We are reusing the method from Hugo. `_internal` is provided by Hugo and added within https://github.com/okkur/syna/blob/master/layouts/partials/js.html#L42 as far as I can see. Will investigate.

**Comment by autodidaddict** [comment]
Yeah I saw that line from the partial, but when I use Firefox or Chrome developer tools to sniff every single line of source that I download from either of my deployed sites using this template, I can't find my analytics code or any reference to the google analytics JS file and I'm not sure why :(

**Comment by stp-ip** [comment]
It's the order. Will push new config.toml versions.

**Comment by stp-ip** [comment]
Updated master, v0.15 and the starter repo. Thanks for reporting.

Also happy for you to open issues with general onboarding, docs etc. feedback :)

**Comment by autodidaddict** [comment]
I just updated my submodule and pulled from master on both my sites, re-deployed, and can still find no evidence of the google analytics code. Can you point me to the exact file (e.g. if I'm in Chrome's inspector) where this shows up?

**Comment by stp-ip** [comment]
I changed the example config, which you modified. So you have to move the `googleAnalytics = ""` code up. See the change here: https://github.com/okkur/syna/pull/579/files

**Comment by autodidaddict** [comment]
Yep that was it. I moved my GA config line up and now both sites have obvious GA code. Thanks!

**Comment by pelloq1** [comment]
Hello

I had to move it higher, above the [languages].

Cédric
