### ISSUE TITLE
multilingual ?

### ISSUE THREAD

**Issue by jodumont** [okkur/syna#580]
Hi;

I tried to make this template multilingual but I'm not an Hugo expert
it is possible to make the template multilingual and/or if it's already the case to explain a little bit or it should be working ?

**Comment by stp-ip** [comment]
Thanks for taking the time to open an issue.
Currently we don't fully support multilingual sites. It should be possible as each fragment is it's own content file and using the Hugo specific split within the content directory should work, but we haven't fully tested this.

If you are testing this out, please provide feedback and we might be able to fix anything that comes up.

There is a feature tracking issue already up: #14

**Comment by stp-ip** [comment]
Some additional notes:

Content translation should work out of the box with the below technique as far as I can see.
Recommendation would be either directory based splitting: https://gohugo.io/content-management/multilingual/#translation-by-content-directory
Or file based: https://gohugo.io/content-management/multilingual/#translation-by-filename

We don't do anything special here so config translation should work as well.
For the config file translation take a look here: https://gohugo.io/content-management/multilingual/#configure-languages

We reuse menus for nav etc. So this should also be possible.
And for menus: https://gohugo.io/content-management/multilingual/#menus

**Comment by joeblew99** [comment]
I am also interested in i18n.

It found it hard to translate hugo sites in general because you have to do it a bit differently depending on the content types. ( config, file, content dir).

I wonder if you could add a more structured wrapper in syna so its easier for mortals to manage the translation ? Maybe in the make file would be a good start ? there you you could have formal wrappers for doing it so people are so so lost.

Maybe later we could add a web GUI for it to make it even easier for mortals.

**Comment by stp-ip** [comment]
In general with Syna is should already be a bit easier as almost everything that is user facing is a content file. So one can split it into en/, de/ etc. directories or specifically per file as far as I can see.

A web GUI is being thought about and might use netlify CMS as a first iteration.

Not sure, what specific makefile wrappers make sense. It might be really tooling specific so harder to implement on a general level. Basically any service/tool doing a per file translation should work.

That being said. It's not fully supported yet, but we would love to add it.

Contributions are always welcome as well ;)
