### ISSUE TITLE
Global fragment not working with member fragment

### ISSUE THREAD

**Issue by emilio1625** [okkur/syna#582]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
I'm creating a site using Syna, according to the docs, i should be able to add a global fragment to a section of my site, for example, the blog, by creating a _global folder and putting there the needed fragments, but this doesn't seem to work with the "member" fragment.
I got this error:

`Currently there is no configured member content files present. To add new members add a content file within blog/_global/author`

inside content/blog/_global/author i already have a index.md and a author.md files

**What you expected to happen**:
Get a member fragment in all the blog posts

**How to reproduce it (as minimally and precisely as possible)**:
1. Setup a syna-start repo
2. Decompress the attached blog folder inside content, which has the following structure:
```
content/blog
├── entry <- all the blog's entry resources
│   ├── content.md <- content fragment 
│   └── index.md
├── _global
│   ├── author
│   │   ├── author.md <- member info
│   │   └── index.md <- member fragment
│   └── index.md
├── _index
│   └── index.md <- list fragment
└── _index.md
```
[blog.zip](https://github.com/okkur/syna/files/3433570/blog.zip)
3. run `hugo server`
4. this results in a failed build with the following error:
` Currently there is no configured member content files present. To add new members add a content file within blog/_global/author`

**Anything else we need to know?**:
There is a way to make this work, but its very annoying, i'll try to explain it the best i can
1. start `hugo server` before creating `content/blog/_global/author/index.md` or comment all its contents
2. Create a new folder `content/blog/entry/author` and put inside a `author.md` with all the info of the author and omit a `index.md`file, also the `content/blog/_global/author/author.md` file must be present otherwise this doesn't work, 
3. Uncomment o create the member fragment in `content/blog/_global/author/index.md`, save 2 or 3 times, the first time you save it Hugo will output the same error, later saves will work fine

I think this is a feature that avoids code duplication and i think my use case is not an edge use case.

Also i was wondering if there is another way to accomplish the same thing using slots, i have seen them been used in the code, but i couldn't find any documentation about them.

**Environment**:
- Syna Theme version:  v0.15.1 and v0.15
- Hugo version:  v0.55.6/extended linux/amd64
- Others:

**Comment by stp-ip** [comment]
Let us know, if this works on latest master for you.

Still needs version v0.55.6 from Hugo. As there is still #584 and #588
