### ISSUE TITLE
[list] Select ordering of a list

### ISSUE THREAD

**Issue by nitmws** [okkur/syna#583]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
When using a list like described in https://about.okkur.org/syna/fragments/list/ the list of pages looks like being ordered by their title. (I can't find a documentation of that on this page.)

**What you expected to happen**:
To be able to set which kind of odering is used as outlined in Lists of Content/Ordering Content of the Hugo documentation - https://gohugo.io/templates/lists/#order-content

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Syna Theme version:  0.15.1
- Hugo version:  0.55.6
- Others:

**Comment by stp-ip** [comment]
Now available within master.
