### ISSUE TITLE
Best practice to change font family

### ISSUE THREAD

**Issue by csajedi** [okkur/syna#587]
Hi, I cant figure out how to update the fonts in this theme to the ones I would like to use for branding. I found the settings I'd like to update in `themes/syna/assets/styles/bootstrap/_variables.scss` but I believe changing them there spells trouble for my submodules setup. Any advice or is this currently not supported?

**Comment by stp-ip** [comment]
You can inject your own custom CSS file that references font families. Custom CSS should be taking precedent.
https://about.okkur.org/syna/fragments/config/

**Comment by mpourismaiel** [comment]
I'll close this issue. Let us know if the solution doesn't work for you.
