### ISSUE TITLE
[cards-repo] Add repo cards for items

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#599]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
We currently use items/item/portfolio for showcasing projects etc.

**What you expected to happen**:
Have an additional card, which can be used with externally propagated data.

**Anything else we need to know?**:
Interesting repository list example. http://sap.github.io

**Comment by mpourismaiel** [comment]
External data in Hugo is a bit challenging. I assume it's best implemented using plugins (if they come). Then we can pull data from any api and merge and flatten and put the data in a fragment. Like how it's implemented in GatsbyJS. I don't have any good ideas for doing so with Hugo except displaying the data dynamically. Is that a good idea?

**Comment by stp-ip** [comment]
Yeah I assume it would be a JS based approach not sure yet on the specifics. Maybe the ability to define an api endpoint and a json field that gets displayed?

Starting with say pulling in github, gitlab and prometheus stats. That's probably 90% of the use-cases. That way as long as one write a program or uses an api that either pipes into prometheus or exposes json themselves it would work.

Just rough ideas for now. Also this is dynamic on the client side instead of building data into the build. 

For that an "offline" or "non 3rd-party" mode would be interesting. Basically we query the endpoints and write the data into the html right away.

**Comment by mpourismaiel** [comment]
Does this look good?

![image](https://user-images.githubusercontent.com/14017717/87857491-62bd1100-c93c-11ea-8c3d-39e5001c3457.png)
