### ISSUE TITLE
Reduce whitespace within Go template

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#60]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
Currently we sometimes cut out whitespace via hugo's `-` operator and mostly we don't.
This leads to non obvious issues with cut out whitespace within html and also to a lot of whitespace in the final html without cutting it out.

**What you expected to happen**:
More optimized html.

Move to using `{- ... -}` everywhere by default. Fix any issues coming up with that change.

**Comment by stp-ip** [comment]
As an additional note:

* netlify doesn't optimize whitespace
* unoptimized index.html is about 75kb (uncompressed) - 7kb (compressed)
* optimized/minimized index.html is about 48kb (uncompressed) - 6kb (compressed

A few options in my view:
* don't reduct whitespace and prefer readable code such as new line for attributes etc.
* reduct whitespace in all cases
* reduct whitespace in some places. Prefer readable code, but reduce the intermittent whitespace between fragments or comments for example.

**Comment by mpourismaiel** [comment]
What about just removing the new lines? There are very few cases where we have something like this:

![image](https://user-images.githubusercontent.com/14017717/40272675-86d8b6d8-5bc6-11e8-8867-75607aabf8c1.png)

And it's not that important to eliminate that whitespace but there are a lot on unnecessary new lines the final output:

![image](https://user-images.githubusercontent.com/14017717/40272683-ad6dbaa0-5bc6-11e8-8290-e2631a4597c0.png)

If we just remove those new lines the final results would be easier to navigate and I guess that's what actually matters. As you said the final output would have no noticeable change in size if optimized and I believe most people would debug the HTML code using debugger in Firefox or inspect in Chrome. Both of which prettify HTML by themselves. Removing new lines would just make it easier to navigate the HTML in View Source page.

It is possible to clean up the HTML using a prettifier tool after the final build as well.

I guess the only problems that might arise are with Netlify with it's form handling which I believe we dealt with. However that fix has messed up VSCode's HTML grammar and syntax highlighting.

**Comment by lauragift21** [comment]
I'd say we look at a possible way to remove/reduce the whitespaces and newlines on the user-facing side like using prettify like @mpourismaiel  suggested not necessarily reconsider whitespace changes in all cases but enable more readable code in the long run.

**Comment by stp-ip** [comment]
Not sure I understand your points correctly.
Proposed:
* remove explicit whitespace removal with go templates in Hugo aka using `-` such as `{- printf "hello world" -}`
* add prettify to dev pipeline

Result:
* without post processing html code is horrible
* dev needs to run post processing steps to prettify code? Does that work with `hugo server`?
* user needs to post process html output after Hugo page generation (additional step)

**Comment by stp-ip** [comment]
Sure, but at which step?
We can do it within Hugo and Go templates, but it sometimes leads to bugs etc.
We can do it after Hugo finished generation of a page, but that adds an additional step and complicates running "hugo server".

**Comment by mpourismaiel** [comment]
Doing so in Go templates would be the better choice but whenever we add a makefile we can add that extra step so the final output would be cleaner.

**Comment by stp-ip** [comment]
Ok let's try to do it in Go templates. This needs a bit of documentation for contributors as to make that clear that whitespace should be reduced.
So it seems we should be rewriting all Go template code from `{ ... }` to `{- ... -}` and fix any issues coming from this.

This would reduce the whitespace around any Go template code, but not yet between pure html.

I'm hesitant to add a post processing pipeline after Hugo.

**Comment by mpourismaiel** [comment]
If we add a make file I guess post processing wouldn't be much of an issue. Although writing a makefile is one of the hardest challenges I've faced to day :D
