### ISSUE TITLE
[content]: Sidebar is not scrollable

### ISSUE THREAD

**Issue by erbesharat** [okkur/syna#601]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
When sidebar is sticky and there is ToC fragment in it, it's not scrollable.

**What you expected to happen**:
The sidebar should be scrollable even if it's sticky.

**How to reproduce it (as minimally and precisely as possible)**:
Enable sticky option in sidebar config and use ToC inside it.

**Anything else we need to know?**:

**Environment**:
- Syna Theme version:  `0.15.0`
- Hugo version:  `Hugo Static Site Generator v0.55.0-4333CC77F/extended linux/amd64 BuildDate: 2019-04-08T17:05:23Z`
- Others:

**Comment by stp-ip** [comment]
So this means we can't make the sidebar scrollable itself?

Thought it might be able to work similarly to https://stripe.com/docs on smaller screens. Their left sidebar is scrollable vertically, if it's overflowing. It's still sticky towards the content so.

Or maybe my use of the term sticky is not correct.
