### ISSUE TITLE
Change template variables to snake case where possible

### ISSUE THREAD

**Issue by mpourismaiel** [okkur/syna#61]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Request for refactor that may prevent bugs

**What happened**:
It seems using camel cased variables don't work properly in Hugo and as in [the documentation for frontmatter in Hugo website](https://gohugo.io/content-management/front-matter/) it seems that they recommend snake cased.

**What you expected to happen**:
I think we should rename the variables from lower case/camel case to snake case.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Syna Theme version:  
- Hugo version:  
- Others:

**Comment by stp-ip** [comment]
Just saw it within the netlify patch. Makes it much more readable compared to the forced lowercase camelCase.
@lauragift21 also agrees that snake_case is good.

Let's to that.

Question remains how far do we want to go? Only use it in hugo specifics aka variables or everything including html id, class, name etc?

**Comment by mpourismaiel** [comment]
I was looking for a convention we can apply globally but couldn't find any. IMHO Let's change every variable to snake case so we would have applied a single convention and not worry about different cases. 

Also maybe it's not a bad idea to add eslint and prettier to our JS code, I'm planning on writing some JavaScript and it's better to have the rules beforehand but that's another matter.

**Comment by stp-ip** [comment]
Ok then snake_case all over it is. For the JS. A linter seems good. Let's track that within another issue.
