### ISSUE TITLE
_index is also added to list items

### ISSUE THREAD

**Issue by AndreSteenbergen** [okkur/syna#610]
bug

**What happened**:
When creating a list, an extra appears. The _index/index.md is added to the list as well. The following image shows my directory listing.
![image](https://user-images.githubusercontent.com/7676790/65505815-69205f00-deca-11e9-96d2-76c4c7d5f5b6.png) I got the following list:
![image](https://user-images.githubusercontent.com/7676790/65505910-a1c03880-deca-11e9-9a2c-bacac491d50b.png)

**What you expected to happen**:
2 items in the list, without the last item

- Syna Theme version:  Latest from git
- Hugo version:  0.58

**Comment by AndreSteenbergen** [comment]
I also see this occuring on the demo page of syna itself:
![image](https://user-images.githubusercontent.com/7676790/65591161-422a6180-df8c-11e9-94a5-88d5afe865e8.png)

**Comment by stp-ip** [comment]
This should have been fixed by #607. Not sure, why it isn't. @mpourismaiel ideas?

**Comment by stp-ip** [comment]
I think this is fixed. The demo page does run on the latest stable aka v0.15.0 so isn't updated yet.
Our own demo doesn't have that issue: https://about.okkur.org/syna/fragments/

Can you check again, if you are running the latest git version? You already mentioned this, but wanted to make sure this is the case :)

**Comment by AndreSteenbergen** [comment]
Ah sorry, I am running 0.15, so I guess it is fixed already.

**Comment by stp-ip** [comment]
Great. Will close this here. Happy for general feedback as well.

We should cut a new release sooner than later it seems.
