### ISSUE TITLE
How would I combine 2 fragments in 1 container?

### ISSUE THREAD

**Issue by AndreSteenbergen** [okkur/syna#615]
I would like to create something in 2 columns. For example a list in the left column and a portfolio in the right column. I know I could create a custom fragment, but still how would I use two existing fragments in that way?

I am reading in the sources about slots. Is that a way to do it? How would that work?

**Comment by stp-ip** [comment]
Currently that's not possible out of the box as far as I can see. @mpourismaiel can correct me on this.

Slots are predefined locations for fragments to interact such as having a 2 column content page with the list on the left and the content on the right.

In general our design focus was mobile, where multiple columns usually aren't working anyway so each fragment is in most cases full width.

There is an open PR, which was thinking about a *grid* fragment, that can show fragments within a customized grid:
PR: https://github.com/okkur/syna/pull/556
Demo: https://deploy-preview-556--syna-demo.netlify.com/fragments/grid/

In my personal view that made the theme too complex and especially error prone, but happy to get more feedback on this.

The goal still is simple theme with a lot of flexibility and most advanced cases being handled within their own fragment.

**Comment by mpourismaiel** [comment]
Currently we don't have any layout fragments that would allow this. As you mentioned you can create a new fragment that would allow this. You need to create the html layout (two columns, `.col-` classes from bootstrap can be used) and register two slots, one in each column.
Content fragment supports a sidebar which registers a slot. You can enable the sidebar and make use of `sidebar` and `before-content` slots in it.
You can register multiple fragments in each slot and they will be sorted by `weight` so you can create an extended page using this method. 
We'll be happy to get feedback on grid fragment as @stp-ip mentioned. Using the grid fragment it's possible to create complex grids (according to bootstrap grid layout) and each grid cell registers a slot.
Let us know if you have any questions.

**Comment by AndreSteenbergen** [comment]
I came up with this in a custom template. It works, but I don't know if I am missing stuff here.

```
{{- $self := .self -}}
{{ if eq .root.Params.Type "Product" }}

{{- $slots := newScratch -}}
{{- range (.page_scratch.Get "page_fragments") -}}
    {{- if and (not .Params.disabled) (isset .Params "fragment") (isset .Params "slot") -}}
        {{ $slots.Add .Params.slot . }}        
    {{- end -}}
{{- end -}}

<div class="gallery-description">
    {{ $gallery := $slots.Get "gallery" }}
    {{- if $gallery -}}
        {{- $file_path := strings.TrimSuffix ".md" (replace $gallery.File.Path "/index.md" "") -}}
        {{- $name := strings.TrimSuffix ".md" (replace $gallery.Name "/index.md" "") -}}

        {{- $context := dict "page_scratch" .page_scratch "root" .root "Site" .Site "page" .page "resources" .page.Resources "self" $gallery "Params" $gallery.Params "Name" $name "file_path" $file_path -}}
        {{- $template := print "fragments/" $gallery.Params.fragment ".html" -}}
        {{- partial $template $context -}}
    {{- end -}}

    {{ $info := $slots.Get "product-topinfo" }}
    {{- if $info -}}
        {{- $file_path := strings.TrimSuffix ".md" (replace $info.File.Path "/index.md" "") -}}
        {{- $name := strings.TrimSuffix ".md" (replace $info.Name "/index.md" "") -}}

        {{- $context := dict "page_scratch" .page_scratch "root" .root "Site" .Site "page" .page "resources" .page.Resources "self" $info "Params" $info.Params "Name" $name "file_path" $file_path -}}
        {{- $template := print "fragments/" $info.Params.fragment ".html" -}}
        {{- partial $template $context -}}
    {{- end -}}
</div>

{{- end -}}
```

**Comment by mpourismaiel** [comment]
That works but you can accomplish the same thing using the slot helper:

layouts/partials/fragments/gallery.html
```
<div class="row">
	<div class="col-6">
		{{ partial "helpers/slot.html" (dict "root" $ "slot" "column-1" "data" (dict)) }}
	</div>
	<div class="col-6">
		{{ partial "helpers/slot.html" (dict "root" $ "slot" "column-2" "data" (dict)) }}
	</div>
</div>
```

content/_index/gallery.md
```
fragment="gallery"
weight=100
```

content/_index/list.md
```
fragment="list"
weight=10
slot="gallery/column-1"

# list fragment params
```

content/_index/portfolio.md
```
fragment="portfolio"
weight=10
slot="gallery/column-2"

# portfolio fragment params
```

Just as an example.

The slot helper adds an slot with the proposed name and passes the data you want to it's child (whatever fragment you add to the slot). Then you can just add the `slot` variable to the fragments you want to display in the columns. You can add multiple fragments to a slot by just adding more files with the same `slot` value. They'll be sorted using the `weight` variable.

This way you can make use of the updates we push to slot helper which may differ in the future.

**Comment by AndreSteenbergen** [comment]
Thanks, that's actually what I was trying to find using the slots in the starting question.
