### ISSUE TITLE
The FAQ fragments too long in the mobile terminal

### ISSUE THREAD

**Issue by tiramisutes** [okkur/syna#620]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
The FAQ fragments too long in the mobile terminal
**What you expected to happen**:
Best to read in the mobile terminal.
**How to reproduce it (as minimally and precisely as possible)**:
When a title is too long, it should breaks lines automatically.
**Anything else we need to know?**:

**Environment**:
- Syna Theme version:  0.15.2
- Hugo version:  0.58
- Others: Windows 10
![long](https://user-images.githubusercontent.com/10768210/67850776-09aa1480-fb44-11e9-87c3-b4dcf79f55b3.jpg)

**Comment by mpourismaiel** [comment]
Fixed by #673
