### ISSUE TITLE
Syna is not fully compatible with Hugo 0.60.0 new markdown render

### ISSUE THREAD

**Issue by Marzal** [okkur/syna#638]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
Hugo [0.60.0](https://github.com/gohugoio/hugo/releases) / 0.60.1 changed  **blackfriday** markdown render to **Goldmark**

**What you expected to happen**:
All the content is rendered

**How to reproduce it (as minimally and precisely as possible)**:
Build the proyect with hugo > 0.60.0

**Anything else we need to know?**:
To [workaround](https://gohugo.io/getting-started/configuration-markup/#configure-markup) this until some changes are made:

Add to config.toml
```
[markup]
   defaultMarkdownHandler = "blackfriday"
```

**Environment**:
- Syna Theme version:  0.15.1 or master
- Hugo version:  0.60.1
- Others: Arch Linux

**Comment by stp-ip** [comment]
Thanks for reporting. Always happy for PRs :)

**Comment by Marzal** [comment]
I found the a official [bug report](https://discourse.gohugo.io/t/hugo-0-60-0-raw-html-omitted-issue/22010/3) in Hugo.
The option to use the new render and RAW html is:
`[markup]`
`  [markup.goldmark]`
`    [markup.goldmark.renderer]`
`      unsafe = true`

**Comment by mpourismaiel** [comment]
Thanks for reporting the issue. We're a bit back on supporting new Hugo versions since there have been quite a few breaking changes. We're investigating ways to work around them but the latest supported version for us right now seems to 0.58.1. Hopefully our next release will add support for latest updates. We always appreciate new PRs.

**Comment by Marzal** [comment]
Just in case this info is useful.
I have not tested all the fragments, but at least with Nav, Item, Search, Portfolio, Content, Embed, Footer and Copyright with `unsafe = true` everything it's working well in the [web](https://residuocerorm.gitlab.io/) were I'm using Syna with Hugo 0.60.1.

**Comment by mpourismaiel** [comment]
I'm not sure why unsafe helps. Anyways, creating a PR for it right away.

**Comment by mpourismaiel** [comment]
If you can explain to me why without `unsafe` nothing renders I would really appreciate it. GoldMark is common mark compliant and  I don't think we're using anything beyond common mark in our markdown files. Except maybe shortcodes in a few places.

**Comment by Marzal** [comment]
`unsafe` allow RAW html with GoldMark, and markdownify is converting the markdown in html before GoldMark tries to render (or at least is what I think)

For example in the item.html fragment the "Title" `{{- .Params.title | markdownify -}}` and all the other Params work, but the content `{{- .self.Content | markdownify -}}` is what is omited/changed for `Raw HTML omitted` because I have an unsorted list that markdonify converts in html which GoldMark doesn't allow by default.
The other calls to markdonwnify are simple sentences that doesn't convert to any html code, just plain words. 
```
title = "Apuntes sobre Zero Waste"
...
+++
* Text
* ... 
* Another text
```
If I change
`{{- .self.Content | markdownify -}}` to just `{{- .self.Content -}}` it work's without needing `unsafe`

I don't know if is better explained in this [bug](https://discourse.gohugo.io/t/hugo-0-60-0-raw-html-omitted-issue/22010/3)

**Comment by mpourismaiel** [comment]
Okay I think changing `{{- .self.Content | markdownify -}}` to `{{- .self.Content -}}` is a much better solution. Created a tracking issue for it #646 so we can investigate all the places it causes problems. I really appreciate your help. I wouldn't have been able to figure this out on my own. Thanks a lot.

**Comment by stp-ip** [comment]
It seems like the actual solution might be setting it to untrue with the reasoning, if one controls the content this should be fine.

Removing markdownify feels like removing most of the good layout structuring from .Content or am I missing some kind of auto markdown layouting?

**Comment by Marzal** [comment]
I'm not sure yet what's the real problem with markdownify, if I use a content with just a plain word in the same place still fails, so is not because of the complexity of the source to translate to html. I will do further testing these days.

**Comment by mpourismaiel** [comment]
@Marzal We appreciate your help. PRs are welcome.
