### ISSUE TITLE
[blog] root path articles not possible

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#650]
**What happened**:
Currently hosting articles on the root path doesn't work.

**What you expected to happen**:
Setup articles within the first level.
blog/some-article vs /some-article.

**Anything else we need to know?**:
This fails as far as I can see due to list only accepting a subpath such as "blog/" and not "/".
Also seems it does default to the current directory for _index, which is not what one wants as _index assumes all things are fragments not pages so each article will show up as a content file.

Needs a bit of thinking, if that is something to support. If this is a problem in our current thinking or what else might be doable.

**Comment by mpourismaiel** [comment]
First level pages are a bit of a problem. We can certainly try and see how it's possible without breaking the fragment strategies. I'll get on it.

**Comment by stp-ip** [comment]
Awesome. Sounds like a challenge :P

**Comment by mpourismaiel** [comment]
As usual, the fix is a letter change in the code. `Section` is not the type for some pages, `section` is. My debugging behavior needs to change.
