### ISSUE TITLE
Markdown not rendered within table

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#671]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
Markdown inside tables don't seem to be rendered.

**What you expected to happen**:
Rendered markdown as before.

**How to reproduce it (as minimally and precisely as possible)**:
https://about.txtdirect.org/docs/placeholders/

**Anything else we need to know?**:
This might also be covered with a test as we ran into this as a regression.

**Comment by mpourismaiel** [comment]
I'm not sure which version of Hugo have been used to build the website. I'm using v0.62.2 and it seems to be working fine. Please use the latest version of Hugo as we seem to be supporting it without anything breaking.
![image](https://user-images.githubusercontent.com/14017717/71903289-feddb280-3178-11ea-8022-b1dc6da60d1f.png)

**Comment by stp-ip** [comment]
Damn might have been a patch fix or something. Will update to the latest hugo and recheck.

**Comment by stp-ip** [comment]
Nothing to do with Syna specifically, but Goldmark/Commonmark.
`**Bold**` doesn't work, but ` **Bold**` works.
Seems like it needs a preceeding whitespace. This feels wrong, but is also present within their spec documentation and in their "try it" demo it doesn't work either (https://spec.commonmark.org/dingus/?text=%3Ctable%3E%3Ctr%3E%3Ctd%3E%0A%3Cpre%3E%0A**Hello**%2C%0A%0A_world_.%0A%3C%2Fpre%3E%0A%3C%2Ftd%3E%3C%2Ftr%3E%3C%2Ftable%3E%0A). Will look into filing an issue with CommonMark.

**Comment by mpourismaiel** [comment]
That's really weird.
