### ISSUE TITLE
[nav] regression in #navbarCollapse

### ISSUE THREAD

**Issue by Marzal** [okkur/syna#677]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
Regression in nav

**What you expected to happen**:
When you click on the nav hamburger it should show the list

**How to reproduce it (as minimally and precisely as possible)**:
Just click on the demo [site](https://about.okkur.org/syna/) with a small windows size

**Anything else we need to know?**:
This is all I could find
### 0.15
**HTML:**
`<div class="navbar-collapse justify-content-between collapse show in" id="navbarCollapse"> `

**Function:**
assets/js/helpers/bootstrap-helper.js
```
function toggleMenu(node) {
  const menu = document.querySelector(node.dataset.target);
  menu.classList.toggle('in');
}
```

### 0.16
**HTML:**
`<div class="navbar-collapse justify-content-between collapse show" id="navbarCollapse">`

**Function:**
assets/js/collapse.js
```
const showCollapse = function (el, target) {
  $(el).attr('aria-expanded', 'true');
  $(el).removeClass('collapsed');
  $(target).addClass('show');
};
```

So the problem seems to be that in 0.16 the new functions don't add the **in** class

**Environment**:
- Syna Theme version:  0.16
- Hugo version:  0.60

**Comment by stp-ip** [comment]
There seems to have been a bigger underlying issue with a code change leading to a full DOM reset resulting in lost event listeners. This should be fixed in #681.

If this is still an issue in master let us know and reopen :)
