### ISSUE TITLE
[ToC]: First level headers doesn't get rendered

### ISSUE THREAD

**Issue by erbesharat** [okkur/syna#682]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
First level headers aka `# Header` doesn't get rendered in ToC.

**What you expected to happen**:
First level headers get rendered and their children get rendered under them.

**How to reproduce it (as minimally and precisely as possible)**:
```
# First Header
## Second Header 
### Third Header
```

**Anything else we need to know?**:
![image](https://user-images.githubusercontent.com/7544732/72267578-8cb41480-3635-11ea-97d4-88d7e0543bc8.png)
The highlighted sections are the first level headers that didn't get rendered.

**Environment**:
- Syna Theme version:  `v0.15.0`
- Hugo version:  `Hugo Static Site Generator v0.61.0-DEV/extended linux/amd64 BuildDate: unknown`
- Others:

**Comment by mpourismaiel** [comment]
For some reason, I'm starting to hate Hugo. 

https://gohugo.io/content-management/toc/

https://gohugo.io/getting-started/configuration-markup/#table-of-contents

**Comment by stp-ip** [comment]
So the recommendation for Hugo in general would be to only use `h2` and down for headers.

Good docs within the response +1
