### ISSUE TITLE
[nav] Support dropdown menu if hasChildren

### ISSUE THREAD

**Issue by data-henrik** [okkur/syna#683]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
child menu is not shown

**What you expected to happen**:
if child entries are present, generate dropdown menu
**How to reproduce it (as minimally and precisely as possible)**:
add menu item with parent reference

**Anything else we need to know?**:

**Environment**:
- Syna Theme version:  
- Hugo version:  
- Others:

**Comment by stp-ip** [comment]
Dropdown menus especially on mobile are problematic. Any specific ideas or inspiration examples for how you would like this to look?

**Comment by data-henrik** [comment]
No specifics, but could expand on hover. For mobile, child menu could be shown when expanding the burger (no dropdown).

**Comment by mpourismaiel** [comment]
Bootstrap's dropdown actually works pretty good on both mobile and desktop. I'm creating a PR which uses the dropdown, although I had to change our dropdown code to prevent title change in navbar as our previous code did.
