### ISSUE TITLE
Responsive menu not working

### ISSUE THREAD

**Issue by pranavchavda** [okkur/syna#691]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
When you click on the hamburger menu at the top-right when on mobile, it doesn't open anything. this is not a problem on desktop and wider screens since the full menu is shown

**What you expected to happen**:
it to slide out and show menu items and search
**How to reproduce it (as minimally and precisely as possible)**:
https://about.okkur.org/syna/ has the same issue however https://syna-demo.okkur.org/ works fine
**Anything else we need to know?**:
The "scroll to top" link that appears after scrolling on the bottom right doesn't work either
**Environment**:
- Syna Theme version:   0.16
- Hugo version:  v0.62.2/extended linux/amd64
- Others:

**Comment by stp-ip** [comment]
This was fixed in current master. We'll be releasing a new version later today or tomorrow.

**Comment by pranavchavda** [comment]
super. thanks! :)

**Comment by stp-ip** [comment]
https://github.com/okkur/syna/releases/tag/v0.16.1
