### ISSUE TITLE
Syna - "contact" fragment - email

### ISSUE THREAD

**Issue by SeidoTakeshi** [okkur/syna#704]
Hi. I'm building a site. I want to add a contact form which, when the button "send" is pressed" send the message directly to a given email address, say "name@example.com"
I'm trying to do that by myself, but if I comment the variable "post_url" email are sent to formspree. If I set "post_url" to "mailto:name@example.com" the message is sent to my email client.
How have I to set the variables of the "contact" fragment to let it send the messages to "name@example.com" without formspree or other services?

**Comment by mpourismaiel** [comment]
You can't directly send email from a web page. You need to create an api that receives the form and sends the email. Formspree is a good default for this functionality and that's why we use it. If you choose to use the api way, just set `post_url` to your api endpoint.
