### ISSUE TITLE
The button "Back to top"

### ISSUE THREAD

**Issue by SeidoTakeshi** [okkur/syna#705]
**Is this a BUG REPORT or FEATURE REQUEST?**:

bug

**What happened**:

The "Back to top" button (the square one with a symbol like a caret floating on the bottom-right of the page when scrolling) don't work.

**What you expected to happen**:

To go to the top of the page when clicking on the button

**How to reproduce it (as minimally and precisely as possible)**:

Go to https://about.okkur.org/syna/ , scroll down the page then click on the squared button

**Anything else we need to know?**:

 I'm on Firefox 70.0.1, Linux 64 bit

**Environment**:
- Syna Theme version:  0.15 (cloned with git)
- Hugo version:  extended 0.63.2
- Others:

**Comment by stp-ip** [comment]
The latest version of Syna is 0.16.1, which has a fix of this issue. Our docs page needs to be rebuilt with the latest version, which should happen soon.

**Comment by stp-ip** [comment]
Page updated.

**Comment by Tadeshi** [comment]
Same problem: https://arahasmas.gitlab.io/psite2/
/themes/syna/VERSION : v0.16.1 ( https://gitlab.com/arahasmas/psite2/-/blob/ba56b5a6be450c15b8f33534601ab87f03d0d899/themes/syna/VERSION )
