### ISSUE TITLE
Fragment "List" don't show items

### ISSUE THREAD

**Issue by SeidoTakeshi** [okkur/syna#706]
**Is this a BUG REPORT or FEATURE REQUEST?**:

bug

**What happened**:

I'm building the site https://arahasmas.gitlab.io/psite2 . The site has the following structure:

- content
  + blog
    - [_index.md](https://github.com/okkur/syna/files/4167274/_index.md.txt)
    - _index
      + [index.md](https://github.com/okkur/syna/files/4167283/index2.md.txt)
      + [list.md](https://github.com/okkur/syna/files/4167290/list.md.txt)
      + [content.md](https://github.com/okkur/syna/files/4167294/content.md.txt)
    - arta
      + [index.md](https://github.com/okkur/syna/files/4167305/index3.md.txt)
      + [content.md](https://github.com/okkur/syna/files/4167311/content2.md.txt)
    - artb (same content as arta)
    - artc (same content as arta)
  + (other pages/sections)

(I've changed the names of the uploaded files to let github accept them). As you can see at https://arahasmas.gitlab.io/psite2/blog/ none of the list item is showed.

The same happen when I preview the site via `hugo server -D`. But if I, during the preview, change the name of an inner directory (say from "arta" to "art12") then automagically the list item appear on the page. So the same with the other inner directories. If I kill `hugo` and restart it again the list item are disappeared from the page. The problem is that the page is badly builded on gitlab and the page "Blog" is showed without list items.

**What you expected to happen**:

To see the list items as a normal fact.

**How to reproduce it (as minimally and precisely as possible)**:

I don't know if on your machines the problem is the same.

**Anything else we need to know?**:

**Environment**:
- Syna Theme version:  
- Hugo version:  
- Others:

**Comment by stp-ip** [comment]
What is your Hugo version and your Syna version?

**Comment by SeidoTakeshi** [comment]
```
$ hugo version
> Hugo Static Site Generator v0.63.2-934EE21F/extended linux/amd64 BuildDate: 2020-01-27T12:20:42Z
```
themes/syna/VERSION = v0.16.1

**Comment by stp-ip** [comment]
Is your sites code available publicly? If yes that might help with debugging.

**Comment by Tadeshi** [comment]
> Is your sites code available publicly? If yes that might help with debugging.

Sure it is: https://gitlab.com/arahasmas/psite2

(Incidentally, github no longer logs me in with my previous account, I had to create a new one just to be able to follow this thread. There are REAL reasons why everyone is moving to gitlab. You too could make a little thought about it.)

**Comment by stp-ip** [comment]
We do have an archival gitlab server hosted ourselves, but currently the community and visibility is still with Github. We also go the namespaces reserved at gitlab.com. So there was thought going into this decision :)

Thanks with the code this should be easier.

**Comment by mpourismaiel** [comment]
@Tadeshi Sorry for the delay.

I'm trying to visit the pages listed in your `content/blog` directory and none of the are accessible. They have a 404 status. It might be because the pages' `index.md` files don't have `title` parameters.

https://arahasmas.gitlab.io/psite2/blog/artc

I'm not really sure why the pages are not created. If the `title` parameter in `index.md` files don't help I'm afraid I don't have any better ideas. That is more of a Hugo problem since Hugo controls what pages are created. And I guess the lack of the page is the reason why the list fragment is empty.

I'm interested in why Hugo is behaving this way. Please update us on how you fixed it and if the problem persists.

**Comment by SeidoTakeshi** [comment]
> I'm interested in why Hugo is behaving this way.
> Please update us on how you fixed it and if the problem persists.

I think (but I'm not sure) I'm on the right way: the fragment list didn't work when I stored into the inner directories (see my first post in this thread) two files: "index.md" and "content.md". But collapsing the two files into one named "index.md" (containing the directives for a "content" fragment") the fragment "list" works as expected.

**Comment by stp-ip** [comment]
Closing as the example code is not accessible anymore. If this persists please open another issue with more details.
