### ISSUE TITLE
The behavior of the fragment "Hero"

### ISSUE THREAD

**Issue by SeidoTakeshi** [okkur/syna#716]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
During the debug related to issue #708 it happened that the header image disappeared. Inside the `/content/global/` directory there is the `hero.md` file with the following instructions:

```
+++
fragment = "hero"
#disabled = true
date = "2020-02-24"
weight = 50
minHeight = "250px"
background = "light" # can influence the text color
particles = false

#title = ""
#subtitle = ""

[Header]
   image = "header.jpg"

[Asset]
   image = "bannertext.png"
   width = "700px" # optional - will default to image width
   #height = "150px" # optional - will default to image height
+++
```

Well, if the following instructions **are not** inside the `config.toml` file

     RelativeURLs = true
     CanonifyURLs = true

the `header.jpg` image appears (but the "back to top" button stops working). If instead those instructions are present in the `config.toml` file, the "back to top" button works, but the `header.jpg` image disappears. This happens both locally and online.

What is strange is that the `bannertext.png` file which is indicated as "asset" in the same `hero.md` file and is kept in the same directory as `header.jpg` does not disappear.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
You can take a look at my [public repo](https://gitlab.com/arahasmas/psite4) on gitlab.

**Environment**:
- Syna Theme version:
  ```
  $ cat themes/syna/VERSION
  v0.16.1
  ```

- Hugo version:  
  ```
  $ hugo version
  Hugo Static Site Generator v0.65.3-211BA42A/extended linux/amd64 BuildDate: 2020-02-23T10:07:00Z
  ```
- Others:

**Comment by SeidoTakeshi** [comment]
Maybe this can be useful:

> If using inline styles, these need to use absolute URLs, for the linked
> assets to be served properly, e.g.
> &lt;div style="background: url('{{ "images/background.jpg" | absURL }}')"&gt;
> 
> Make sure not to use a forward slash / in the beginning of a URL,
> because it will point to the host root and Hugo will not generate
> the correct URL for the demo's assets.
> 
> If using external CSS and JS from a CDN, make sure to load these
> assets over https. Please do not use relative protocol URLs in your
> theme's templates.

([Common permalink issues](https://github.com/gohugoio/hugoThemes/blob/master/README.md#common-permalink-issues))

**Comment by SeidoTakeshi** [comment]
I modified the 15th line of the `/themes/syna/layouts/partials/fragments/hero.html` file as follows:

```html
background-image: url ({{ partial "helpers/image.html" (dict "root" $ self "asset" .Params.header) }})"
```

it becomes

```html
background-image: url ({{ "images/header.jpg" | absURL }})"
```

Now the site works properly. \o/

However, this is a non-general and non-abstract solution, which only works on my installation. I hope you will welcome my proposal to debug the `fragments/hero.html` file.

**Comment by stp-ip** [comment]
Great that you have a workaround. If you want to be a bit less breaking. Instead of changing the Syna theme site you should be able to overwrite just the hero.html file as Hugo has support for this.

Create the modified copy of hero.html to yoursite/layouts/partials/fragments/hero.html.

That way you are still up to date with Syna, but your fix is applied. After this is resolved upstream you can just remove the modified file from your site. This separates the patch much cleaner and also works for other modifications as well.

**Comment by stp-ip** [comment]
This should be fixed with the recent fixed around relative urls.

If this is still an issue with v0.17.0 or later please feel free to reopen.

**Comment by keraint** [comment]
I have the same issue with Syna 0.17.2 and `CanonifyURLs = true`. My website url has the model example.com/syna.
