### ISSUE TITLE
Fragment "items": title  doesn't render correct with text + asset

### ISSUE THREAD

**Issue by k9ert** [okkur/syna#717]
bug

Consider this snippet:
```
+++


title = "Agile"

weight = 10

[asset]
image = "scrum.svg" 

+++

<p>One step at a time will guide us to the moon. Adjusting direction in regular intervals is key to effectively navigate. Having happy customers is the ultimate goal. Check out the <a href="https://agilemanifesto.org/">Agile Manifesto</a>.</p>
```
This renders like this:

![image](https://user-images.githubusercontent.com/117085/75977665-d05c2980-5ed4-11ea-825c-32c5a93a0d27.png)

Doesn't look that nice. I helped myself with this workaround:
```

+++


title = ""

weight = 10

[asset]
image = "scrum.svg" 

+++

<br><br><br><br>
<h4>Agile</h4>
<br>

<p>One step at a time will guide us to the moon. Adjusting direction in regular intervals is key to effectively navigate. Having happy customers is the ultimate goal. Check out the <a href="https://agilemanifesto.org/">Agile Manifesto</a>.</p>
```

which renders much better (Will add screenshot later).

**Comment by stp-ip** [comment]
I can't reproduce this. Can you send me the svg for this and the html code it outputs?

**Comment by scotus-49** [comment]
I have exactly the same problem with a standard .jpg image - the text is rendered under the centre of the image and above the title. The output html code for the column:
```
  <div class="col-md-4 d-flex flex-column">
      <a href="/##" class="col justify-content-between d-flex flex-column header ">
      <div class="row image justify-content-center align-items-center">
            <img src="/images/theme2.jpg" class="p-2 w-75 mb-2" alt="Column 1">
      </div>
      <div class="row justify-content-center text-center">
          <h4 class="mb-3 text-secondary">Column 1</h4></div>
      </a>
    <div class="row justify-content-center text-center p-2">
        <div class=" text-secondary">
          <p>Further description for &ldquo;items&rdquo; 1 column 1</p>
        </div>
    </div>
  </div>
```
I am using Hugo v0.70.0-7F47B99E/extended linux/amd64 with syna theme version 0.17

**Comment by scotus-49** [comment]
Solved.
Place images in the same folder as the .md files. I did this after examining the example site code, and the images were resized and properly positioned. I had previously located my images in the static/images folder.

**Comment by k9ert** [comment]
I had placed the file on the static-folder as well but moving didn't help. I've created a PR which got deployed from netlify here:
https://5ebc55404fea0b4b022ef690--bitcoin-devops.netlify.app/

The branch (and that specific folder) is here:
https://github.com/k9ert/bitcoin-devops/tree/rendering_issue/content/_index/approaches

**Comment by abrain** [comment]
@k9ert (Hi Kim, long time no see 😄) SVG files don't get cropped/resized, even if they are in the same folder as the .md file. You could try another format like PNG, but given the aspect ratio of the icons, I think you won't be happy with the 300 x 110 cropped version anyway? I'm having the same issue and I'll probably go with a modified `items` fragment that allows for square images.

**Comment by mpourismaiel** [comment]
As far as I can see, this is an issue with our CSS. The flex properties are somehow responsible but I can't find a solution on how to preserve the look and fix the issue.
