### ISSUE TITLE
Email error in contact form (even with e-mails received)

### ISSUE THREAD

**Issue by Joezzef** [okkur/syna#718]
Bug

**What happened**:
On the contact form (using Formspree), I am always getting error on the interface ( "Message could not be send. Please contact us at mail@example.com instead."). Even if the e-mails are well received.

**The JS error seems to be:** 

Access to XMLHttpRequest at 'https://formspree.io/thanks?next=https%3A%2F%2Fxxxxxxxx.github.io%2Fcontact%2F&language=fr' (redirected from 'https://formspree.io/xeqzlywp') from origin 'https://xxxxxxxx.github.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

jq-helpers.js:174 GET https://formspree.io/thanks?next=https%3A%2F%2Fxxxxxxxxxgithub.io%2Fcontact%2F&language=fr net::ERR_FAILED 

**What you expected to happen**:

Success message (especially because the e-mails are well received)

**How to reproduce it (as minimally and precisely as possible)**:

- Using contact form from the example site
- Account freshly created on formspree
- New form created. 
- Using post_url provided in the new form. 

**Environment**:
- Syna Theme version:  0.15
- Hugo version:  0.67.1

Thanks for this amazing theme by the way :)

**Comment by stp-ip** [comment]
Please try to update to version 0.16.1 first. This might have been fixed there afaik.

**Comment by Joezzef** [comment]
Thanks for the reply ! 
I have tested with v0.16.1. It now works and the form send button redirect to a formspree template page. 

Just one comment : 
I was using v0.15 because of the documentation here : https://about.okkur.org/syna/docs/installation/#adding-syna-to-your-site
"# Latest release as of now is v0.15"

**Comment by stp-ip** [comment]
Ah good catch. Seems like we missed that docs piece.
We'll update this for the next release, which should be later today.

**Comment by stp-ip** [comment]
Installation instructions are updated to v0.16.2 now. Thanks for reporting again.
