### ISSUE TITLE
partials/helpers/fragments.html:121:64 error calling GetPage: page reference "//blog/_global" is ambiguous

### ISSUE THREAD

**Issue by Cloud-Forge** [okkur/syna#719]
Is this a BUG REPORT or FEATURE REQUEST?:
bug

What happened:
getting the following error as I build since last hugo update :

    partials/helpers/fragments.html:121:64 error calling GetPage: page reference "//blog/_global" is ambiguous

What you expected to happen:
the site should build normally but it doesn't.

How to reproduce it (as minimally and precisely as possible):
To reproduce create a blog section with a _global directory in it.

```
  blog
    _global
      index.md
      nav.md # Rendered
      contact.md # Rendered
```

launch a build command

    hugo

Anything else we need to know?:

I think that the problem comes from the line 120 in **fragments.html** we have this 
```
{{- $page := printf "%s/%s" $directory "_global" -}}
````
the **%s/%s** might be problematic here
the **$page** variable now contains :
**//blog/_global** 
instead of simply  **/blog/_global**

The change I made to be able to build my site was just to remove the **%s/** and now it prints the right path :  **/blog/_global** with only one **/** at the beginning.

Environment:
-  Syna Theme version: v0.16.1
-  Hugo Static Site Generator v0.66.0/extended linux/amd64 BuildDate: unknown
-  Others: Arch linux

**Comment by Cloud-Forge** [comment]
As of now, I did some testing, and it appears that this bug is present at several places, but it always comes down to the same issue. ( //dir/path instead of /dir/path)

If you try to build the sample web site you'll get the error in the **nav.html helper**:
`execute of template failed: template: partials/helpers/fragments.html:121:64: executing "partials/helpers/fragments.html" at <$default_site.GetPage>: error calling GetPage: page reference "//docs/_global" is ambiguous`

**Comment by stp-ip** [comment]
Which Hugo version did work beforehand?
Generally feels like another breaking change by Hugo. Glad you already have a workaround and happy for us to investigate.

Thanks for reporting.

**Comment by Cloud-Forge** [comment]
I am not sure which version did break Syna.
since on my system,  Hugo is updated through the Arch package manager and did not do any builds on all the intermediate versions between 0.63 and 0.66.

but I know for sure that the **0.63** was working fine.

**Comment by stp-ip** [comment]
This seems to work fine with the latest Hugo 68.3. Assumption is this was a break in version 0.66 and the related issue is this one: https://github.com/gohugoio/hugo/issues/7016

Let me know, if updating to the latest Hugo version fixes this.
Please reopen, if it isn't fixed.

**Comment by Cloud-Forge** [comment]
Yes it works fine with the last hugo version. Thanks

**Comment by midzer** [comment]
I still have the ambigous bug with 0.68.3:

A have a section `gruenwald` in

`content/cities/gruenwald/`

and a page `gruenwald` in

`content/cities/foo/bar/gruenwald.md`

Thanks in advance for looking on the issue :)

**Comment by stp-ip** [comment]
Assumption is you are using `ref` somewhere to call the gruenwald page or?

Then you have to be more specific on the ref: `{{< ref "cities/foo/bar/gruenwald" >}}

If my assumption wasn't correct and the ambiguous issue isn't `error calling GetPage: page reference "//blog/_global" is ambiguous` then please open another issue with a bit more context.

**Comment by Cloud-Forge** [comment]
My 2 cents : 
Your error might not be related to the bug. 
The "ambiguous" error is also a real error that appears when Hugo cannot choose the path of your page, because you didn't give a specific path.

You'll have to show use more code and more logs to see whether it's the bug or an oversight.
