### ISSUE TITLE
Contact form button misaligned when using recaptcha

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#722]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
Filler space is creating issues with the button alignment.

**What you expected to happen**:
Centered submit button.

**How to reproduce it (as minimally and precisely as possible)**:
https://about.rekkur.com/#contact

**Anything else we need to know?**:

**Environment**:
- Syna Theme version:  v0.16.2
- Hugo version: v0.68.3

**Comment by mpourismaiel** [comment]
Recaptcha is aligned left in the provided link and the button is centered. Should it change to another configuration?

**Comment by stp-ip** [comment]
For me the button isn't centered see:
![Screenshot from 2020-04-18 15-51-19](https://user-images.githubusercontent.com/3768412/79642367-8e3d2d80-818c-11ea-9c88-a96a4cd4c29f.png)

**Comment by stp-ip** [comment]
Just checked. Firefox issue it seems. Or at least Chrome doesn't have that issue. :roll_eyes:

**Comment by mpourismaiel** [comment]
Maybe it's a version issue? Are we checking the same page?

https://about.rekkur.com/#contact

For me the recapcha is showing but in your screenshot it's not visible.

![image](https://user-images.githubusercontent.com/14017717/79694232-4b5e8100-8284-11ea-99cd-eb1b18f14950.png)

**Comment by stp-ip** [comment]
It's a when recaptcha is blocked or doesn't load then the misalignment happens.

**Comment by stp-ip** [comment]
Moving this to the next milestone for now.
