### ISSUE TITLE
Optional unsplash hero image

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#73]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
Currently either the default image, no image or a custom image are shown.

**What you expected to happen**:
Automatic rotating images via unsplash api.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
This is a long term non priority feature. It probably also needs some design work to make the test readable with any background image color etc.

Some info on unsplash: https://unsplash.com/developers

**Comment by mpourismaiel** [comment]
Unsplash API requires the developer to implement the API in a way that is not automated (so user can see and select the image they want), allows the user to visit the image's page on Unsplash and show the copyright (I think that stands for all their images, although if you download and use the image without tribute, it's okay). I'm not sure how to implement the non-automated part though. Maybe let the user select the id they want from the Unsplash website? Definitely not random image, that's not allowed by them.

**Comment by stp-ip** [comment]
Mhh ok. Maybe they changed their API requirements. I was thinking about something like this: https://apps.nextcloud.com/apps/unsplash

Also Nomadlist uses unplash and a search query to get custom city images.

**Comment by stp-ip** [comment]
Let's close this for now.
