### ISSUE TITLE
date_format param does not work for publish dates although used in partial

### ISSUE THREAD

**Issue by kaistierl** [okkur/syna#736]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
I set following in `config.toml`:

```
[params]
  date_format = "02.01.2006"
```

But this did not change the date format.

**What you expected to happen**:

Since the `publish-date.html` helper partial contains this
```
{{- $date.Format ($.site.Params.date_format | default "2006-01-02") -}}
```
I expected the date format to change.

**How to reproduce it (as minimally and precisely as possible)**:

Just do the same config as I did

**Anything else we need to know?**:

If I understood it right, partials seem to have an isolated scope and no access to outer scope. This could mean it's not possible at all inside a partial to use `$.site.Params`. This could be the root-cause.
See https://gohugo.io/templates/partials/#variable-scoping

**Environment**:
- Syna Theme version: `v0.16.2`
- Hugo version: `Hugo Static Site Generator v0.68.3/extended darwin/amd64 BuildDate: unknown`
- Others:

**Comment by stp-ip** [comment]
Found the issue. Will push a PR fixing it up in a sec.

**Comment by stp-ip** [comment]
You can test this without patching syna directly by adding the fixed file within your site's layout folder:

Add below content to `<your-site>/layout/partials/helpers/publish-date.html`
```
{{- $date := .root.Date | default .root.Lastmod }}
{{- $date_format := .root.Site.Params.date_format | default "2006-01-02" }}

{{- if not (eq .badge false) }}
  <span class="publish-date badge mr-1
    {{- if (eq $.background "dark") -}}
      {{- printf " badge-%s" "light" -}}
    {{- else -}}
      {{- printf " badge-%s" "primary" -}}
    {{- end -}}">
    <time datetime="{{ $date }}" itemprop="datePublished dateModified">
      {{- $date.Format $date_format -}}
    </time>
  </span>
{{- else }}
  <span class="publish-data mr-1 badge
    {{- if (eq $.background "dark") -}}
      {{- printf " badge-%s" "light" -}}
    {{- end -}}">
    <time datetime="{{ $date }}" itemprop="datePublished dateModified">
      {{- $date.Format $date_format -}}
    </time>
  </span>
{{- end -}}
```

**Comment by kaistierl** [comment]
This works for me! Thanks a lot for the lightning-fast help 🙂

**Comment by stp-ip** [comment]
Great will leave it open until the PR is merged and the next version is released ETA around 23rd of each month.
