### ISSUE TITLE
Allow hCaptcha in addition to reCaptcha

### ISSUE THREAD

**Issue by tjgruber** [okkur/syna#741]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
I am unable to use reCaptcha due to some reasons besides the point, and would like to use hCaptcha instead. However, when I put in the site key, it gives an error.

**What you expected to happen**:
I expected it to "just work" had it been supported.

**How to reproduce it (as minimally and precisely as possible)**:
Sign up at hCaptcha, input the "sitekey" appropriatly as shown in the example at:
https://about.okkur.org/syna/fragments/contact/

**Anything else we need to know?**:
I think it would be great to be able to specify captcha method, such as:
captcha = "hCaptcha"

**Environment**:
- Syna Theme version:  
- Hugo version:  
 Current versions of both Hugo and Syna.

**Comment by stp-ip** [comment]
We would be open to accept a PR for this.
