### ISSUE TITLE
Opposite language selection on start page /

### ISSUE THREAD

**Issue by schoettl** [okkur/syna#759]
Thank you for this theme!

**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
I set up a multi-lingual site. English is default language. Translations works for all pages except for `content/_index/`.

As soon as I `cp _index/index.md _index/index.de.md`, the home page is empty for the default language, and in English for the German "de" version. In short:

- `/` is empty except for *German* nav/footer.
- `/de/` is non-empty and in English, only nav/footer is German.

It's totally the opposite, but only for the homepage?!

**What you expected to happen**:
`/` should be English
`/de/` should be in German

**How to reproduce it (as minimally and precisely as possible)**:
Do you already have a guess? Otherwise I have to setup a new project to create a minimal example.

**Anything else we need to know?**:
- Maybe `languageCode` plays a role? It's configured under each language.
- I did `rm -rf resources public`
- I pressed Ctrl-F5 in browser

**Environment**:
- Syna Theme version: master branch from github 2020-05-14
- Hugo version:  0.70.0
- Arch Linux

**Comment by schoettl** [comment]
Wait, now it works again. It took me an hour, moving files, playing with config, ...

Two things I did:

- Moving the `menu` config under the default language config. Before that, it was defined globally and under the secondary language config.

- I had a copy of the `_index` folder with *both* languages. I first named it `xx`, then I moved it outside the `content` directory.

**Comment by stp-ip** [comment]
Interesting. This does feel like a bug and most likely comes from our theme specific code making the idea of fragments work on the index page etc.

No specific solution in my mind yet.

**Comment by schoettl** [comment]
Does it help, if I provide a minimal example based on https://git.okkur.org/syna-start ? As a patch or a GitHub fork?

**Comment by stp-ip** [comment]
A minimal example showcasing the issue already helps. Based on syna start seems reasonable as it does have a lot less moving parts. You can link to a branch on your fork for this.

Thanks for helping out.

**Comment by mpourismaiel** [comment]
Not sure how this was happening, it might have something to do with `params.DefaultContentLanguage` which might not have been set. Set it to your default language. Not that we require this value in addition to Hugo's own `DefaultContentLanguage` (which is located in the top section of the config file).
