### ISSUE TITLE
Theme fails to build in hugo version 0.71.1 (0.71.0 works fine)

### ISSUE THREAD

**Issue by Houndie** [okkur/syna#773]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
Attempting to build site with syna theme with hugo v0.71.1 results in error message:

```
Error: Error building site: failed to render pages: render of "page" failed: "/path/to/project/themes/syna/layouts/_default/baseof.html:10:9": execute of template failed: template: _default/single.html:10:7: executing "_default/single.html" at <partial "helpers/fragments-renderer.html" (dict "page_scratch" .Scratch)>: error calling partial: "/path/to/project/themes/syna/layouts/partials/helpers/fragments-renderer.html:10:9": execute of template failed: template: partials/helpers/fragments-renderer.html:10:9: executing "partials/helpers/fragments-renderer.html" at <(not (isset .Params "slot")) (ne .Params.slot "")>: can't give argument to non-function not (isset .Params "slot")
```

**What you expected to happen**:
Site builds correctly

**How to reproduce it (as minimally and precisely as possible)**:
* Install theme on site
* Try and build site with hugo v0.71.1

**Anything else we need to know?**:
Works fine with hugo v0.71.0.  Unsure if this is syna doing something it shouldn't or this is a regression on hugo's side.  Scanning through the code in the latest changelog, and looking at the error message, it seems like it's related to [these changes](https://github.com/gohugoio/hugo/commit/6c3c6686f5d3c7155e2d455b07ac8ab70f42cb88#diff-981fbfeb374ac30e53aac700cbc33234L32). (that link may not link correctly due to github not wanting to render the diff by default, look for file " tpl/internal/go_templates/texttemplate/funcs.go")

Probably going to open an issue with hugo as well given that it seems like a regression on their side.

**Environment**:
- Syna Theme version:  
sha 5bbd985
- Hugo version:  
0.71.1
- Others:

**Comment by stp-ip** [comment]
Thanks for catching this. As mentioned this feels like a regression from a first look especially during a Hugo patch release. Let's wait for a response from Hugo and happy to dive into any possible fixes once we know more.

**Comment by Houndie** [comment]
According to the hugo devs, hugo 0.71.1 now catches a construct that always "illegal" but was let slide.  I submitted a PR above that fixes the offending template.
