### ISSUE TITLE
livereload.js not found on GAE

### ISSUE THREAD

**Issue by romain-berthe** [okkur/syna#793]
**BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
The website perfectly works locally, but once pushed on Google AppEngine, I have a 404 error on livereload.js. and my SVG images are not loaded.

**What you expected to happen**:
All JS files should be located on my "public/script" folder but I cannot found the livereload.js file.

**How to reproduce it (as minimally and precisely as possible)**:
Here is my app.yaml file:

`runtime: python37

instance_class: F1

handlers:

- url: /
  static_files: www/public/index.html
  upload: www/public/index.html
  secure: always
  redirect_http_response_code: 301

- url: /membres
  static_files: www/public/membres/index.html
  upload: www/public/membres/index.html
  secure: always
  redirect_http_response_code: 301

- url: /tarifs
  static_files: www/public/tarifs/index.html
  upload: www/public/tarifs/index.html
  secure: always
  redirect_http_response_code: 301

- url: /cnntact
  static_files: www/public/contact/index.html
  upload: www/public/contact/index.html
  secure: always
  redirect_http_response_code: 301

- url: /about
  static_files: www/public/about/index.html
  upload: www/public/about/index.html
  secure: always
  redirect_http_response_code: 301

- url: /*.css
  static_dir: www/public/
  mime_type: text/css
  secure: always
  redirect_http_response_code: 301

- url: /images/.svg
  static_dir: www/public/images/
  mime_type: image/svg+xml
  secure: always
  redirect_http_response_code: 301

- url: /scripts/.js
  static_dir: www/public/scripts/
  mime_type: application/javascript
  secure: always
  redirect_http_response_code: 301

- url: /(.*)
  static_files: www/public/\1
  upload: www/public/(.*)
  secure: always
  redirect_http_response_code: 301`

**Anything else we need to know?**:
How the livereload.js is generated ? I'm not even able to locate this file locally (but can get it when I call https://localhost:1313/livereload.js

**Environment**:
- Syna Theme version: Last
- Hugo version: Last

Thanks !

**Comment by romain-berthe** [comment]
I found my answer, livereload is used to reload the website content each time we apply a modification.

It is not related to my SVG issue.

**Comment by stp-ip** [comment]
Yeah livereload is a Hugo thing helping during development.
It's only injected with the development server and not with the final static files.
