### ISSUE TITLE
Error: Error building site: TOCSS: failed to transform "main.scss"

### ISSUE THREAD

**Issue by certik** [okkur/syna#796]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:

```
$ cd themes/syna/exampleSite
$ hugo --ignoreCache
Building sites … WARN 2020/07/09 16:58:09 .File.Dir on zero object. Wrap it in if or with: {{ with .File }}{{ .Dir }}{{ end }}
Total in 540 ms
Error: Error building site: TOCSS: failed to transform "main.scss" (text/x-scss): resource "scss/styles/index.scss_a4e369375f17bb89f2019364cbe7a830" not found in file cache
```

If you remove `--ignoreCache` then it works.

**What you expected to happen**:

I expected the website to regenerate the cache.

**How to reproduce it (as minimally and precisely as possible)**:

See above.

**Anything else we need to know?**:

**Environment**:
- Syna Theme version:  2826c48e1a456da37a78e6727c80ea2dc78aee1b
- Hugo version:  v0.69.0-4205844B
- Others: Ubuntu 18.04

**Comment by ukorn** [comment]
This affects me too.

Syna Theme version: https://github.com/okkur/syna/commit/2826c48e1a456da37a78e6727c80ea2dc78aee1b
Hugo version: 0.73.0-428907CC windows/amd64
Others: Windows 10 2004

**Comment by mpourismaiel** [comment]
Are you using Hugo extended version? We build SASS files and do other build processes that are only possible in Hugo extended version. We build files with every change to our assets to make sure users without extended version of Hugo can still build their websites but that requires you to not use `--ignoreCache`.

If you're already using extended version, please let me know how to reproduce the issue. I am able to build the project without any issues.

**Comment by ukorn** [comment]
Solved it for me,

thanks a lot.

**Comment by certik** [comment]
I verified that downloading Hugo extended fixed this issue. I haven't heard of the extended version until now.

**Comment by mpourismaiel** [comment]
Happy to hear it works. Extended version has Sass and Postcss and stuff like that allowing to unify most of the build process. Nothing special really.
