### ISSUE TITLE
Particles option wont work on multilang

### ISSUE THREAD

**Issue by pelloq1** [okkur/syna#798]
First of all, this theme is awesome ! Great job !

bug 

**What happened**:
The particles option wont work if multilang is enabled. Console : 

```
particles.js:18 Uncaught TypeError: Cannot read property 'offsetWidth' of null
    at new pJS (particles.js:18)
    at window.particlesJS (particles.js:1517)
    at eval (hero.js:9)
    at Array.forEach (<anonymous>)
    at eval (hero.js:6)
    at Object../assets/js/hero.js (syna-hero.min.97a3fff0c67d9da74ebdd6af2640d8a9cde6200539e8c3b2c091b7fc6644420e.js:7)
    at __webpack_require__ (syna-hero.min.97a3fff0c67d9da74ebdd6af2640d8a9cde6200539e8c3b2c091b7fc6644420e.js:2)
    at syna-hero.min.97a3fff0c67d9da74ebdd6af2640d8a9cde6200539e8c3b2c091b7fc6644420e.js:4
    at syna-hero.min.97a3fff0c67d9da74ebdd6af2640d8a9cde6200539e8c3b2c091b7fc6644420e.js:5
```

**How to reproduce it (as minimally and precisely as possible)**:
If I use the multilang option and generate my site in EN and FR, on the FR version the particles aren't visibles.

- Syna Theme version:  v0.17.2
- Hugo version:  0.72

Thanks Cédric

**Comment by mpourismaiel** [comment]
Is there a place we can see the source code for the project? I can't reproduce the issue. I'm using our own demo. A step by step reproduction would help as well.

**Comment by pelloq1** [comment]
Simply create a multilingual version of the demo site, in the _index folder duplicate the hero.md in hero.fr.md 

```
+++
fragment = "hero"
#disabled = true
date = "2016-09-07"
weight = 50
background = "light" # can influence the text color
particles = true

title = "Titre"
subtitle = "Votre partenaire depuis 1987"

[header]
  image = "header.jpg"

[asset]
  image = "logo.svg"
  width = "500px" # optional - will default to image width
  #height = "150px" # optional - will default to image height

+++

```

Let me know if you can fix this, then I can apply the fix before the 0.18 release

👍

**Comment by mpourismaiel** [comment]
Okay this is happening in `syna-start` and for some reason doesn't happen in `syna`. Correct me if I'm wrong, the problem arises with or without multilingual mode. Please pull a new version of `syna-start` and run it and let me know.

**Comment by pelloq1** [comment]
Sorry, I do this : 

 hugo new site test
 installing the 0.17 Syna based ont the documentation's guide
 copy my old content and config.toml
 

particles works on english version /
does not work on french version   /fr

Sorry for this ...

**Comment by pelloq1** [comment]
Please see my last post in #799 this is a very similar issue.

Cédric

**Comment by mpourismaiel** [comment]
Not sure about #799, but #801 will fix this issue. I'll check #799 with the new PR shortly.

**Comment by pelloq1** [comment]
Hello,

I need to reopen this issue. I cannot have the particles.js working on sublanguage versions of site.

I put a temporary version of the site here http://abacus.abouc.ch 

In Fr (main) the particles work, but not in EN/DE.

Is there a quick fix I can (manualy) apply ?

Thanks
