### ISSUE TITLE
Multilingual mode and page of type : items / faq

### ISSUE THREAD

**Issue by pelloq1** [okkur/syna#799]
bug ? (I dont know if is a bug or if I do something wrong)

**What happened**:
In the list fragment I have : 

 - services/index.fr.md
 - services/index.fr.md
 - services/list-tiled.md
 - services/list-tiled.fr.md

In the list-tiled.* I have defined the source : 
section = "services-folder1"

In the services-folder1 I have : 
 - sample1.md
 - sample1.fr.md
 - sample2.md
 - sample2.fr.md

It work fine in french and english

If I try to do the same with the faq or items fragments, that dont work, the page is simply not rendered and in place the home page is shown.

**Environment**:
Syna Theme version: v0.17.2
Hugo version: 0.72

Thanks Cédric

**Comment by stp-ip** [comment]
Might be a bug. Thanks for reporting. Multilingual mode is still in its earlier stages so all bug reports are helpful.

**Comment by pelloq1** [comment]
Thanks. 

I can find a temporary workaround for the FAQ page by creating 2 different pages folder.

But I use the items (with the font awesome) on the home page ( as on syna sample), and there I cannot bypass. 

Any idea?

Thanks
Cédric

**Comment by mpourismaiel** [comment]
It was a bug. Please wait for #800 to be merged. After that you can create faq to items fragment the same way you'd define them in single language websites, but add `index.fr.md` and `column1.fr.md` along with `index.md` and `column1.md` in your items fragment's directory.

**Comment by pelloq1** [comment]
Hi,

I dont understand, I have chaged NOTHING and it work now ???

Except the faq page that is continuing to not working...

**Comment by stp-ip** [comment]
Try pulling the latest theme from master:

```
cd theme/syna
git checkout origin master
```

Also what specifically does work now? Sometimes the Hugo cache is a bit weird with out use of fragments and changes don't show up after a full reload. Maybe that could have been it?

**Comment by pelloq1** [comment]
Excellent !

It work fine now ! 

You rock ! 👍 👍 👍

**Comment by pelloq1** [comment]
Hello,

Sorry to re open this thread, but when I open the french FAQ, I cannot open the collapsed items : 

```
jq-helpers.js:14 Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Document': '#faq/index.frfaq/question1.fr-collapse' is not a valid selector.
    at $ (webpack:///./assets/js/helpers/jq-helpers.js?:14:108)
    at showCollapse (webpack:///./assets/js/collapse.js?:43:27)
    at HTMLDivElement.eval (webpack:///./assets/js/collapse.js?:30:5)
```

Maybe is the same case as : #798  

Thanks you.
Cédric

**Comment by mpourismaiel** [comment]
Hopefully our new PR fixes the problem. If it's possible, please test the PR before we merge it. It would help us a lot.
