### ISSUE TITLE
Create search fragment

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#8]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
No search fragment.

**What you expected to happen**:
Simple search fragment.

**How to reproduce it (as minimally and precisely as possible)**:
Look for a search fragment.

**Anything else we need to know?**:
Look into index.js + lunr.js

**Environment**:
- Syna Theme version:  v0.7.0
- Hugo version:  v0.30.2

**Comment by mpourismaiel** [comment]
There doesn't seem to be any `lunr.js` file. I think it's removed.

Should the search be done using Google?

**Comment by stp-ip** [comment]
lunr.js was just an idea to have client side search.
Basically search support could be split up into 2 issues. One is client side minimal search using the index.js generated by hugo and the other one would be server side search using Google or probably Algolia.
