### ISSUE TITLE
Add Intercom solution/showcase

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#80]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
Currently intercom isn't supported in Syna.

**What you expected to happen**:
Add fragment that adds intercom widget to the page.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
All aspects should be contained within the specific fragment.

**Comment by stp-ip** [comment]
They have 14 days trial periods. Will click you one after this week. If I forget, ping me on it ;)
Also that would be a good use case for the "inject" or so fragment. Having the ability to inject a script or style into the page via a fragment.
That way we could reuse that fragment for intercom.

Then we can have intercom as an example for that inject fragment. Does that make sense?

Also that might warrant us to create a separate /use-cases/ or /showcase/ directory later. Where we showcase what is possible with different fragments. Basically not show the developer view aka `list`, but the user view aka `blog` or in this case not `inject`, but `intercom`.

Happy to hear your thoughts. Got a bit sidetracked.

**Comment by mpourismaiel** [comment]
Seems like a great idea, we can use it to add piwik for example. GA is built in, I would've liked to make that optional as well.

This would be a great starter issue since it's not the hard. It just needs to be forced to the end of fragments list which is not that important. A simple fragment that would render the `.Content` into a script tag.

**Comment by stp-ip** [comment]
.Content into a script tag or take a url for external linking I assume.

**Comment by stp-ip** [comment]
Changed.

How should we name the use cases? Use case, showcase, solution?

**Comment by mpourismaiel** [comment]
I think showcase would be fine.

**Comment by stp-ip** [comment]
Ok so intercom doesn't have developer accounts or a sandbox environment. Relying on a trial without continued possibility to test it between releases it feels wrong to add it here.
The solution from the intercom support was: Don't use/offer intercom. :man_shrugging:
