### ISSUE TITLE
Broken stylesheet on Hugo Themes demo

### ISSUE THREAD

**Issue by jwarner112** [okkur/syna#804]
**Is this a BUG REPORT or FEATURE REQUEST?**:

bug

**What happened**:

Went to https://themes.gohugo.io/theme/syna/ and it's broken

**What you expected to happen**:

The stylesheets to download and for the page to look like https://about.okkur.org/syna/

**How to reproduce it (as minimally and precisely as possible)**:

https://themes.gohugo.io/theme/syna/

**Anything else we need to know?**:

Screenshot (with Console Log):
![image](https://user-images.githubusercontent.com/2992409/87990699-61edc180-ca99-11ea-93a9-99c88734d454.png)

**Environment**:
- Syna Theme version: [syna @ 8976bf0](https://github.com/okkur/syna/tree/8976bf0da78fa4b557ebda00fb0477e357c33dea)
- Hugo version: latest deployed version
- Others:
  - Browser: Firefox 78.0.2 (64-bit)
  - OS: Linux 5.3.0-62-generic #56~18.04.1-Ubuntu

**Comment by jwarner112** [comment]
I thought this might have just  been my fault but a friend on another machine (w/ Chrome) confirmed this link is broken; What I _think_ is happening is the file doesn't exist so `gohugo.io` is returning a 404 page that's then parsed as `text/html`.

**Comment by mpourismaiel** [comment]
The asset's path is wrong. Not sure why. @stp-ip Would you please check this out?

**Comment by stp-ip** [comment]
Checking it out. Thanks for the bug report.

**Comment by stp-ip** [comment]
The asset path works, when using Permalink instead of RefPermalink within head.html. Still trying to figure out the full picture as there are various other annoyances related to this issue.
