### ISSUE TITLE
Simple documentation fragment

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#81]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
Currently hosting documentation with Syna is manual.
 
**What you expected to happen**:
Documentation fragment. Rendering simple markdown documentation via Syna as a docs fragment.

**Anything else we need to know?**:
Take markdown files -> render within fragment
Additional options:
* search (docs only?)
* submenu to browse docs

**Comment by stp-ip** [comment]
So content fragment can already be used as documentation.
Search is in the works.
Missing seems to be the submenu to browse the docs similar to: 
![screenshot-material-docs_hu8ba7b9cad870a1ade7612e6323d38122_252037_750x500_fill_catmullrom_top_2](https://user-images.githubusercontent.com/3768412/44961019-4f942a00-aef9-11e8-8139-a4b85f13a698.png)

Specific option for the sidebar? Aka have a submenu for browsing if enabled? Does that make sense? Could it be structured differently?

**Comment by mpourismaiel** [comment]
I think fragment in fragment can help here as well. I think since we have helpers now it can be done using a new helper and taking advantage of the fragments helpers. Not sure how but I think it's doable and not that complicated. Not sure how it will look to the user though.

**Comment by stp-ip** [comment]
Hehe I was thinking that idea would come up here :D 
Definitely something we should discuss after v0.14.0

**Comment by mpourismaiel** [comment]
We can do this without fragment in fragment with adding an extra functionality to content fragment, allowing side to render content headers inside it. That way all the doc would be inside one page but the feature wouldn't be any more complex.

**Comment by stp-ip** [comment]
I think we should start it without fragment in fragment for now. Could be an option in sidebar such as `navigation`, `filetree` or so?

**Comment by mpourismaiel** [comment]
I think this can be considered done since we went ahead with the fragment in fragment idea and implemented Syna's own documentation with that technique. I'm closing this issue. Let me know if there are any problems.

**Comment by stp-ip** [comment]
I have a personal handbook for notes etc, which used material docs theme from hugo, when I have some spare time I'll port it over and can grab some more feedback. For now this seems implemented and ready \o/
