### ISSUE TITLE
Read more link stays on the same page

### ISSUE THREAD

**Issue by damienjegou** [okkur/syna#831]
Hi,

Trying to make a blog with Syna, I found that "Read more" link after the summary of an article sends to the current page (articles list) instead of the article page.
Clicking on the title works correctly, displaying the full article.

You can see the bug on okkur.org blog : https://blog.okkur.org/articles/ 

Thank you for this nice theme.
Damien.

**Comment by stp-ip** [comment]
Good catch. We are still catching up on everything (hell of a year), but it's on the radar now. Always happy for PRs so :)
