### ISSUE TITLE
unable to overwrite the favicon.ico

### ISSUE THREAD

**Issue by JOduMonT** [okkur/syna#835]
As usual, I created a favicon.ico which contains 3 layers with GIMP and I saved it inside ./static/images/ with favicon.png and favicon.svg

While favicon.svg and favicon.png superseed Syna logo, favicon.ico doesn't.

I tried
- in private mode with Brave and Firefox, to be sure it is not cached by the browser
- hugo server --ignoreCache
- hugo server --disableFastRender
- rename everything favicon.* to logo.* and adjust the name in config.toml

all these attempts failed.

**Environment**:
- Syna Theme Starter version:  version = "0.17.3"
- Hugo version:  Hugo Static Site Generator v0.75.1-A4A7BAB7/extended linux/amd64 BuildDate: 2020-09-15T06:57:20Z
- Others: Ubuntu 20.04 LTS Brave and Firefox
![image](https://user-images.githubusercontent.com/5204724/98197814-2f89a680-1f5a-11eb-9367-1e692e2bdac3.png)

PS: I also opened the issue [here](https://github.com/okkur/syna-start/issues/44), please tell me where it is the best to follow ;)

**Comment by stp-ip** [comment]
Try adding the favicon.ico in `static/`. Assumption would be that the browser looks at the default location aka the root of the page and not the location the header describes.
Might be a good documentation item to add, if it works.

**Comment by JOduMonT** [comment]
@stp-ip thank for your light,
![image](https://user-images.githubusercontent.com/5204724/98313899-6ec20100-2007-11eb-83eb-ad64e029dca8.png)

**Comment by stp-ip** [comment]
Ah missed that your files were in static/images. They need to be in static/ or referenced as images/favicon.ico in the config.

**Comment by JOduMonT** [comment]
> Ah missed that your files were in static/images. They need to be in static/ or referenced as images/favicon.ico in the config.

Doh I missed that too, thank to your eyes :)
