### ISSUE TITLE
See more blog pages

### ISSUE THREAD

**Issue by buenlimon** [okkur/syna#842]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Feature request, or just a question if the feature is already there.

**What happened**:
I have made a blog. It works fine. On the "list.md" file it says "count = 10". This can be changed to some other number. I then see 10 posts. Ort the other number of posts I have changed the setting to be.

**What you expected to happen**:
I would expect a button to show "see older posts"

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Thank you so much for this software.

**Environment**:
- Syna Theme version:  0.17.4
- Hugo version:  0.74.3
- Others: Ubuntu 20.10

**Comment by stp-ip** [comment]
Pagination is available with list, but it needs to be within a list page. 
This blog post walks you through the default setup of a blog. Happy to help and also happy for additions we could add to the documentation.
https://blog.okkur.org/articles/create-syna-blog/

**Comment by stp-ip** [comment]
Let me know, if this is not solved and reopen :)
