### ISSUE TITLE
Portfolio problem

### ISSUE THREAD

**Issue by buenlimon** [okkur/syna#843]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
I try to make a portfolio page. I have coded index.md and individual subitems like first-item.md, second-item.md etc. These however do not show up on the page when "hugo serve -D" is run. Hugo complains that there is no page with a "content" fragment.

No problem. I include the word "content" in the subitem file like this:

+++ 
weight = 20
#fragment = "subitem"
title = "Empfangsbereich" 
subtitle = "Der erste Kontakt mit der Firma" 
item_url = "#"
[asset]
  image = "wo1.jpg"
+++

Some Text underneath the picture

**What you expected to happen**:
So I thougt this would give me the tiled appearance of the portfolio. But it doesn't. Instead, it gives what is described above - a normal "content". This subitem is not rendered as a portfolio subitem. It is rendered as a normal content.

So I called it "subitem" instead of "content". Hugo denies to render it. What must I do?

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
I am so sorry to bother you with this. It is a remarkably beautiful software for which I am sincerely grateful.

**Environment**:
- Syna Theme version:  0.17.4
- Hugo version:  0.74.3
- Others: Ubuntu 20.10

**Comment by stp-ip** [comment]
The portfolio fragment consists of 2 separate file "types".
One is the portfolio fragment and one are the items.
Initializing the portfolio fragment would be done with something like this:
```
+++
date = "2018-07-09"
fragment = "portfolio"
weight = 110
background = "secondary"

title = "Portfolio Fragment"
subtitle = "Displaying animals with links and modals"
#title_align = "left" # Default is center, can be left, right or center

#height = "110px" # Default is auto
+++
```

Then you can populate the various items with something like this:
```
+++
weight = 10
title = "First Title"
subtitle = "Lorem ipsum dolor sit amet, consectetur adipiscing"
item_url = "#"
#disabled = true

[asset]
  image = "cat-1.jpeg"
+++

Ante in nibh mauris cursus mattis molestie a iaculis. Nisi porta lorem mollis aliquam. Eu consequat ac felis donec et odio pellentesque diam volutpat. Arcu dui vivamus arcu felis. Senectus et netus et malesuada fames ac turpis egestas sed. Orci eu lobortis elementum nibh.
```

The structure is usually a directory for that portfolio fragment, that include both the initializing file as well as the various subitems.

Happy for feedback on the documentation to make this easier.

**Comment by stp-ip** [comment]
Let me know, if there is still anything unclear or a potential bug. Closing for now. Please reopen, if anything else comes up.
