### ISSUE TITLE
Update and automate fontawesome dependency

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#85]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
Currently we manually added fontawesome.

**What you expected to happen**:
Automate via tooling.

**Anything else we need to know?**:
https://fontawesome.com/

**Comment by mpourismaiel** [comment]
@stp-ip With #102 I believe this is fixed. Also before that SVG icons were from packages from NPM.
