### ISSUE TITLE
git.okkur.org ssl certificate expired

### ISSUE THREAD

**Issue by jerusdp** [okkur/syna#857]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug 

**What happened**:
Cannot sync from release store at git.okkur.org because the site's ssl certicate expired on 20th July 2021.

**What you expected to happen**:
Sync latest version of Syna code.

**How to reproduce it (as minimally and precisely as possible)**:
Attempt git submodule sync

**Anything else we need to know?**:

**Environment**:
- Syna Theme version:  
- Hugo version:  
- Others:

**Comment by stp-ip** [comment]
Thanks for flagging. This should update automatically, but it seems Caddy did run into a weird issue. Looking into upgrading the backing service (txtdirect.org) to Caddy v2 in the future. A bit time strapped.

Either way all certs should be reissued and be automatically updated, but will keep an eye on it to be sure.
