### ISSUE TITLE
Breadcrumb level issue ?

### ISSUE THREAD

**Issue by pelloq1** [okkur/syna#858]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug ?

**What happened**:
I enabled the breadcrumbs for my site.

Some menus are based on blog like : 
https://www.abacustranslations.ch/en/services/legal-translations/

For this page, my breadcrumb show : 

Abacus Translations Ltd > Legal translations

**What you expected to happen**:
In a perfect world, this should appear:
Abacus Translations Ltd > **Services** > Legal translations

 -> to easy navigate back.

**How to reproduce it (as minimally and precisely as possible)**:
Simply browse on 
https://www.abacustranslations.ch
Services 
Select one in the list below 

**Anything else we need to know?**:
Maybe I do a mistake ...

I take the english version, for more confort, but the issue is on 3 languages.

Thanks you 
Cédric

**Comment by stp-ip** [comment]
Not sure what goes wrong. Our demo breadcrumb does seem to work with multiple levels, but maybe this is an issue with multiple languages.
Can you reproduce this with a simple example site?
Demo: https://syna-demo.okkur.org/dev/blog/article-1/

**Comment by pelloq1** [comment]
On your sample, from where come the "blog" word ? is a folder name or is set anywhere in a config file ?

**Comment by stp-ip** [comment]
The code is available here: https://github.com/okkur/syna/tree/master/exampleSite/content/dev/blog
It's a subdirectory including a _index.md making it a branch page not a leaf, if I got the terminology from Hugo right.

**Comment by pelloq1** [comment]
My bad, shame on me.

Sorry

**Comment by stp-ip** [comment]
No worries. If you think it was mostly a documentation issue, we are always happy for contributions.
