### ISSUE TITLE
Every time I try to use the items fragment I get this error

### ISSUE THREAD

**Issue by Sleuth56** [okkur/syna#860]
**BUG REPORT**:

Copied strait from the website.
```
+++
fragment = "items"
#disabled = false
date = "2017-10-04"
weight = 110
background = "secondary"

title = "Items Fragment"
subtitle= "Column based items with icons"
#title_align = "left" # Default is center, can be left, right or center
+++
```

`ERROR 2021/12/19 11:46:11 Currently there is no configured items content files present. To add new members add a content file within _index/find
.File.Dir on zero object. Wrap it in if or with: {{ with .File }}{{ .Dir }}{{ end }}`

**Environment**:
- Syna Theme version:  v0.17.4
- Hugo version:  v0.89.4+extended

**Comment by stp-ip** [comment]
Did you also copy in the subdirectory with the single items? Without those it's an empty shell.
The zero object is an error that shouldn't be present I agree. Usually comes up due to Hugo changing backwards compatibility in how the define things.
Happy for any PRs, if you want.

**Comment by Sleuth56** [comment]
I didn't see the part about the sub directory. Thank you for pointing that out. It works great now.
