### ISSUE TITLE
Social media footer links broken on deployment

### ISSUE THREAD

**Issue by spearw** [okkur/syna#872]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:

On deployment to S3, social media links in the Footer fragment are broken. Instead of linking to the social media page, they create a relative link with the website URL first, followed by the social media page.

**What you expected to happen**:

Social media links correctly link to the appropriate page

**How to reproduce it (as minimally and precisely as possible)**:

Deploy a website and follow a social media link from the footer fragment (does not occur in local 'hugo server' site)

**Anything else we need to know?**:

The fix I found is changing layouts/fragments/footer.html

line 30:              <a href="{{ .URL | relLangURL }}" class="ignore-color-change

to this:

line 30:               <a href="{{ .URL | absLangURL }}" class="ignore-color-change

Changing from a relative URL to an absolute URL seems to solve this issue. Happy to create a PR and implement the fix if given push access. 

**Environment**:
- Syna Theme version:  
- latest
- Hugo version:  
- 76.5
- Others:

**Comment by stp-ip** [comment]
Fixed in #873.
Thanks
