### ISSUE TITLE
fatal: unable to access 'https://git.okkur.org/syna/': OpenSSL SSL_read: Connection was reset, errno 10054

### ISSUE THREAD

**Issue by panda2tv** [okkur/syna#879]
### What happened?

d:\hugo\site\test.com>git submodule add https://git.okkur.org/syna themes/syna
Cloning into 'D:/hugo/site/test.com/themes/syna'...
fatal: unable to access 'https://git.okkur.org/syna/': OpenSSL SSL_read: Connect
ion was reset, errno 10054

### What did you expect to happen?

the theme syna suppose to be cloned to local

### How can we reproduce this issue?

try below at local:

git submodule init # If you haven't initialized before
git submodule add https://git.okkur.org/syna themes/syna

### Is there anything else we need to know about?

I am using VPN, if that matter.

**Comment by stp-ip** [comment]
Works for me. Might be an SSL/TLS cert not having propagated correctly to all worldwide servers. Will check this manually. 
Please recheck in a few minutes.

**Comment by panda2tv** [comment]
I work around the issue by using SHH clone. Don't understand the reason but works now.
