### ISSUE TITLE
Make navigation a fragment

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#89]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
Currently the navigation is "hardcoded" and hidden, when empty.

**What you expected to happen**:
Migrate navigation to its own fragment.

**Anything else we need to know?**:
Navigation fragment would enable stacked navigation and per page navigation.

Needs a bit of thinking.
How to use with auto hide feature?
Where should the menu config be set?
How does it work within the current navigation config from Hugo?
Set menus in config.toml, but set used menu in each fragment?
Too much complexity for multi page sites, that just need one navbar? <-- workaround with a global navbar fragment?

**Comment by mpourismaiel** [comment]
Do you have any ideas on how to implement fragment by fragment menus?

**Comment by mpourismaiel** [comment]
@stp-ip @lauragift21 If you have any ideas I would be glad to hear them. I have none!
