### ISSUE TITLE
Create payment fragment (stripe)

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#9]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
No payment fragment.

**What you expected to happen**:
Payment fragment based on stripe.

**How to reproduce it (as minimally and precisely as possible)**:
Look for a payment fragment.

**Anything else we need to know?**:
Also needs backend component hosted.

**Environment**:
- Syna Theme version:  v0.7.0
- Hugo version:  v0.30.2

**Comment by digitalcraftsman** [comment]
out of interest: what do you expect will users sell on their website?

**Comment by stp-ip** [comment]
Could be support subscriptions for open source projects (that's where I want to use it actually).

But could also be eBooks, Music, design work, freelance work etc.

**Comment by mpourismaiel** [comment]
- [ ] Create a event fragment
- [ ] Create a payment fragment
- [ ] When event fragment is in the page, create a pubsub and register every action on the page in it
- [ ] Use the pubsub to connect payment fragment to actions in pricing fragment
- [ ] Register url changes (or hashbang in the url) in the pubsub
