### ISSUE TITLE
Move background style config to fragments

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#90]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
Currently background style for footer and navbar are set within config.toml.

**What you expected to happen**:
Set these within their respective fragments.

**Comment by mpourismaiel** [comment]
@stp-ip I think this one should be closed since the config is already available in the respective fragments and the problem lies with partials and I don't think there's a solution for those.

**Comment by mpourismaiel** [comment]
@stp-ip I'm gonna close this. Open it if the issue is still valid.

**Comment by stp-ip** [comment]
config.toml still has background_footer, which is unnecessary.
