### ISSUE TITLE
Introduce global fragments

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#92]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
With the idea of making everything into a fragment the theme becomes really modular and powerful, but it also opens up sites to use a lot of duplication and complexity.

**What you expected to happen**:
Introduce a way to set global fragments.

**Anything else we need to know?**:
How could something like that look like and work?
A few options in my mind:
1. inject/add: global/navbar.md -> injects itself into all pages as additional fragment
2. default: global/navbar.md -> injects itself into all pages, that don't have a specific fragment yet
3. overwrite: global/navbar.md -> overwrites all fragments with the global config

**Comment by mpourismaiel** [comment]
I'm not sure how one fragment can be injected to all the other fragments. Do you have any resources on the matter?

**Comment by stp-ip** [comment]
That would be done with Go templates. Similar how we check for per page fragments, we could inject global fragments. Difficult to say how it's implemented specifically without a decision on the user "UI".

Currently we say fragments are stored in each page's subfolder aka about-us/hero.md or about-us/hero/index.md.
We force index/* to be special and act as the index/root page.
We could therefore also "force" global_or_whatever/* to be injected into every page depending on the user "UI".

**Comment by stp-ip** [comment]
[WIP - comment]
Trying to clarify the general idea of global fragments and in that context fragments in general.
I'll try to use various user examples.

1. Single page website (most common case):
The user configures the page minimally via index.md and uses fragments for the content and other parts of the page such as contact form, hero, navigation etc.

No other pages are necessary making global fragments unnecessary.

Working with or without global fragments. -> Easy for a user to get started.

2. Single page website with about page:
The user configures 2 pages. The common fragment would most likely be copyright and navigation.

Current solution: Duplicate fragments on both pages or symlink them.
New solution: Introduction of global fragments.

3. Multi page website:
Various pages with common fragments most likely being copyright and navigation.

Current solution: Duplicate fragments on all pages or symlink them.
New solution: Introduction of global fragments.

From a user UI perspective there are various ways to have global fragments.
1. mark fragments within `index/` as global (mixes per page and global fragments --)
2. add global fragment config to config.toml (inconsistent configuration for fragments --)
3. don't add global fragments and document duplication/symlinking (seems like a workaround --)
4. add special directory `global/` to configure global fragments (introduces a new special case)

From an implementation perspective the 3. option is the easiest as this works already with the current code. Option 4 needs extra code and might introduce some issues concerning the ordering.
