### ISSUE TITLE
Simplify code and helper snippets via shortcodes

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#95]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
Currently we have quite a bit of duplication in the various fragments.

**What you expected to happen**:
Reduce duplication and move helper snippets into shortcodes.

**Anything else we need to know?**:
https://gohugo.io/templates/shortcode-templates/

**Comment by mpourismaiel** [comment]
@stp-ip What parts of code should be shortcodes?

**Comment by stp-ip** [comment]
The code part to handle resources for global, page and fragment. Basically having to use the various assignments and loops within each layout seems like too much duplication.
So we could have a shortcode to load images, but instead of doing it normally we would extend it to look for 3 locations fragment > page > global/static.

There might be other things we want to optimize into shortcodes, but that was the most obvious, I thought.

**Comment by mpourismaiel** [comment]
With #118 that part of code would only be used in `single` layout. Although if we let the user customize `404` page it would be nice and then we need to use shortcodes. Considering that should I implement the feature now or wait for 404 to use fragments as well?

**Comment by stp-ip** [comment]
The resource code is only used in hero for now. Only for the logo.
This should be roled out (probably after being a shortcode) to:
* nav logo
* hero background image
* footer logo
* item* images

Might have forgotten a few, but this might be behaviour we want to not duplicate in each.

**Comment by stp-ip** [comment]
Also yes making 404 actually nice looking would be a start and in the same breath turning it into a fragment sounds good. That would also enable to have a search fragment in there later etc.

**Comment by stp-ip** [comment]
Probably would push that to post 0.11 so. It's not essential to a site working.

**Comment by stp-ip** [comment]
Shortcodes are not supported in layouts, using partials looks worse than code duplication.
Going with code duplication for now and researching a better hugo way to do that.

**Comment by stp-ip** [comment]
Not actionable specifically. We already migrated a few of the newer fragments to use helper partials. This should continue and if necessary actionable issues should be separately opened.
