### ISSUE TITLE
Github icon not working within star button (navbar)

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#99]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
Currently the Github icon doesn't work on the demo.

**Comment by stp-ip** [comment]
For me the usual Github icon doesn't work. It's showing a !? instead. Didn't debug it yet. Just wanted to file the bug already before I forget ^^

**Comment by stp-ip** [comment]
My assumption would be that, while we automated the font library, we also updated it and the convention on how to call brand icons changed somehow or we need to especially reference brand icons in the automation.

**Comment by lauragift21** [comment]
Oh, right I see what you mean.
